### ISSUE TITLE
Use GPU on Jetson nano

### ISSUE THREAD

**Issue by grunk** [DoubangoTelecom/ultimateALPR-SDK#102]
Hi,
i'am running the benchmark available in the [binaries](https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/binaries/linux/aarch64) on a jetson nano.
This is working , but it seems to run exclusively on the CPU (4 cores @ 100%). As a consequence the framerate is pretty low (~13fps) lower than the pixel 3a (android) which manage to get 17fps.

Here is the command i used : 

```
benchmark ^
    --positive ../../../assets/images/lic_us_1280x720.jpg ^
    --negative ../../../assets/images/london_traffic.jpg ^
    --assets ../../../assets ^
    --openvino_enabled false ^
    --openvino_device CPU ^
    --klass_lpci_enabled false ^
    --klass_vcr_enabled false ^
    --klass_vmmr_enabled false ^
    --charset latin ^
    --loops 100 ^
    --rate 0.2 ^
    --parallel true
```

Is there something i can do to quickly evaluate your sdk with the GPU instead ? From what i understand setting openvino to false should fallback to tensorflow and use the GPU right ?

**Comment by DoubangoTelecom** [comment]
This is a known issue on Jetson Nano and TX2. There is no GPU acceleration for now. This is scheduled for the version 3.1. In fact there we even don't have CPU optimization for CPU on Jetson for the simple reason that it's not officially supported

**Comment by grunk** [comment]
Ok thanks.
I'll try again when the version is available.

**Comment by DoubangoTelecom** [comment]
Duplicate of #108
