### ISSUE TITLE
Trial version (non-commercial): Your license doesn't allow running the code this long

### ISSUE THREAD

**Issue by Tobias-Fischer** [DoubangoTelecom/ultimateALPR-SDK#109]
Hello,
I'm a researcher and want to use your SDK. As far as I understand the code can be used for non-commercial purposes without a license key. However, I get the following error message after some time: "Your license doesn't allow running the code this long". Does that mean I cannot continue to use the SDK anymore?

Many thanks,
Tobias

**Comment by DoubangoTelecom** [comment]
Hi, you will need to restart the app to reinit the counter. There is a maximum frame the app will process before rejecting the request if no license is provided.

**Comment by Tobias-Fischer** [comment]
Hi, thank you for your response. I am using the Python version - is there any way to reset this? Is there a license for non-commercial use to avoid this issue?
