### ISSUE TITLE
klass_vbsr_enabled - not working

### ISSUE THREAD

**Issue by vlkc** [DoubangoTelecom/ultimateALPR-SDK#119]
Hello, when I run recognizer.bat it reads all data, but not recognize Vehicle Body Style. Is this function does not work?

`*[ULTALPR_SDK INFO]: Processing done.
*[ULTALPR_SDK INFO]: result: {"duration":477,"frame_id":0,"plates":[{"car":{"bodyStyle":[{"confidence":99.42403,"klass":-1,"name":"h*****"},{"confidence":0.4206982,"klass":-1,"name":"v*****"},{"confidence":0.1130586,"klass":-1,"name":"b*****"},{"confidence":0.02529594,"klass":-1,"name":"s*****"},{"confidence":0.007493525,"klass":-1,"name":"c*****"}],"color":[{"confidence":94.11338,"klass":-1,"name":"w*****"},{"confidence":5.574076,"klass":-1,"name":"s*****"},{"confidence":0.1811525,"klass":-1,"name":"b*****"},{"confidence":0.07441306,"klass":-1,"name":"g*****"},{"confidence":0.02451356,"klass":-1,"name":"p*****"}],"confidence":100.0,"makeModelYear":[{"confidence":85.93359,"klass":-1,"make":"chevrolet","model":"c*****","year":"0-9"},{"confidence":8.683008,"klass":-1,"make":"chevrolet","model":"s*****","year":"0-9"},{"confidence":1.36108,"klass":-1,"make":"volkswagen","model":"t*****","year":"0-9"},{"confidence":0.4989869,"klass":-1,"make":"chevrolet","model":"s*****","year":"0-9"},{"confidence":0.4538836,"klass":-1,"make":"ford","model":"e*****","year":"0-9"}],"warpedBox":[532.7416,4.543818,1368.66,4.543818,1368.66,516.2226,532.7416,516.2226]},"confidences":[89.1385,99.36216],"country":[{"code":"LTU","confidence":52.61353,"klass":51,"name":"Lithuania"},{"code":"AUS","confidence":34.66228,"klass":10,"name":"Australia"},{"code":"ITA","confidence":5.206231,"klass":46,"name":"Italy"},{"code":"POL","confidence":2.073822,"klass":62,"name":"Poland"},{"code":"KOR","confidence":1.356814,"klass":49,"name":"Republic of Korea"}],"text":"JNF24*","warpedBox":[1081.8,442.7741,1188.19,442.7741,1188.19,479.7604,1081.8,479.7604]}]}
*[ULTALPR_SDK INFO]: Press any key to terminate   @@!!`

In your website info returns almost correct:
`Color:  white 98.97
Plate:  JNF241 88.63 99.97
Country:  Lithuania 98.65
Body style:  heavytruck 99.74
Make:  chevrolet 60.53
Model:  chevy van 60.53
Color:  white 95.76`

Config file:
`recognizer.exe ^
    --image D:\Nuotraukos\2020.12.28\10_24_26_233_JNF241_ID_2.jpg ^
    --assets ../../../assets ^
    --charset latin ^
    --car_noplate_detect_enabled false ^
    --ienv_enabled true ^
    --openvino_enabled true ^
    --openvino_device CPU ^
    --klass_lpci_enabled true ^
    --klass_vcr_enabled true ^
    --klass_vmmr_enabled true ^
    --klass_vbsr_enabled true ^
    --parallel false`

[File is here](https://easyupload.io/w2aqq7)

What do I miss?

**Comment by vlkc** [comment]
Confidence score - edit.

**Comment by DoubangoTelecom** [comment]
The body style from the sdk is correct. H*** is heavy truck. You get *** because you're using a trial version with no license.
