### ISSUE TITLE
Memory Leaks in TF_NewSession

### ISSUE THREAD

**Issue by PolywickStudio** [DoubangoTelecom/ultimateALPR-SDK#120]
I'm getting thread handle leaks

UltimageAlprSDK:UltraALPRSDKResult - UltimateALPR-SDK.dll 
- TF_NewSession - tensorflow.dll
- MSVCP140.dll - Thrd_Start
- BeingThreadEx - urtbase.dll

Is there a way to free the threads allocated by Tensorflow.dll when UltAlprSdkEngine::init initializes?

UltAlprSdkEngine::init();
...
UltAlprSdkEngine::deInit();

// Thread handle leak not freed.

![alpr](https://user-images.githubusercontent.com/8903532/103356319-90ada080-4aeb-11eb-95c4-2180868187a2.PNG)

**Comment by DoubangoTelecom** [comment]
These are global threads and they are tied to the process and they are not leaked. That means they will only die when the process is terminated. 
You can try:
```
LOOPS = 10;
for (size_t i = 0; i < LOOPS ; ++i) {
   init();
   deinit();
}
```
you'll end up with the same number of threads regardless `LOOPS` value
This is explained at https://github.com/tensorflow/tensorflow/issues/29217
