### ISSUE TITLE
Realtime in Xavier-NX

### ISSUE THREAD

**Issue by PiyalGeorge** [DoubangoTelecom/ultimateALPR-SDK#129]
Hi, Is it possible to run the live camera input for License plate recognition in Xavier-NX at 30FPS(OR near realtime fps) ?

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c%2B%2B/benchmark/README.md#peformance-numbers

**Comment by DoubangoTelecom** [comment]
You'll need to use C++ or a language with support for parallel processing. We do NOT recommend Python for real-time or high-performance apps.
Using C++ you can expect 152fps when there is no plate on the stream (detection only) and up to 54fps when there is a plate (detection and OCR). These numbers may be slightly lower when you have other processes running in the background and eating the CPU ressources
