### ISSUE TITLE
Last character is always a Asterisk

### ISSUE THREAD

**Issue by marcelocferdeveloper** [DoubangoTelecom/ultimateALPR-SDK#13]
Hi. It is some error or it´s a Mask that you put in the code ?
I am trying to use your example, but the last plate character is always an "*"

**Comment by DoubangoTelecom** [comment]
Hello,
You're using a trial version and this is one of the limitations.

**Comment by marcelocferdeveloper** [comment]
Ok. But the Trial is just because I am using the example or even for the SDK if I develop by myself ?
Sorry,  but I am not finding nothing saying about it.

**Comment by DoubangoTelecom** [comment]
So, you haven't checked the most important file in a project https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/LICENSE

**Comment by marcelocferdeveloper** [comment]
I sent a message to your e-mail. Thanks
