### ISSUE TITLE
OpenVINO with Myriad

### ISSUE THREAD

**Issue by VizDock** [DoubangoTelecom/ultimateALPR-SDK#133]
Hi 
Yesterday I managed to get my hands on Intel Movidius Myriad X VPU Compute Stick 2, and decided to check how it works if in example I set OpenVINO device to myriad. Platform is Windows 10 x64.
First it didn't wanted to start OpenVINO at all, complaining that usb-ma248x.mvcmd is missing.

Then I copied usb-ma2450.mvcmd and usb-ma2x8x.mvcmd from c:\Program Files (x86)\IntelSWTools\openvino_2020.3.341\inference_engine\bin\intel64\Release\ directory to directory from where I'm running a program (because I found this link
[https://github.com/openvinotoolkit/openvino/issues/1343](url)

Then when I started example software, I heard a sound from PC like when I run the Intel example (like when you plug in USB device), and at first in console it wrote that OpenVINO is initialized, but few lines later it says it's not.
But CPU is working at half speed compared to when I run same example without stick. 
Intel demo application that comes with OpenVINO toolkit executes OK without error
Could it be that I need to download specific version of openVINO toolkit?
Or if I download latest, can I replace files that you distribute with your SDK which are part of Intel's OpenVINO toolkit?

[PLUGIN_OPENVINO INFO]: OpenVINO inference engine number: 2020.3.1-3500-68236d2e44c-releases/2020/3, version: 2.1
*[COMPV INFO]: [UltAlprDetector] We have managed to create OpenVINO detector/classifier. Ignoring Tensorflow detector/classifier.
*[COMPV INFO]: [CompVSharedLib] Loaded shared lib: D:\VSprojects\example\bin\Debug\ultimatePluginOpenVINO.dll
***[PLUGIN_OPENVINO ERROR]: function: "pluginOpenVinoInferenceEngine::newInstance()"
file: "source\plugin_openvino_inference_engine.cxx"
line: "314"
message: OpenVINO error: Can not init Myriad device: NC_ERROR
*[PLUGIN_OPENVINO INFO]: ~pluginOpenVinoInferenceEngine
***[PLUGIN_OPENVINO ERROR]: function: "pluginOpenVino_Engine_new()"
file: "source\plugin_openvino_inference_engine_dll.cxx"
line: "96"
message: Failed to allocate engine
***[COMPV ERROR]: function: "ultimateAlpr::UltAlprPlugin::newObj()"
file: "source\ultimate_alpr_plugin.cxx"
line: "449"
message: Operation Failed (COMPV_ERROR_CODE_E_THIRD_PARTY_LIB) -> Failed to create OpenVINO engine
***[COMPV ERROR]: function: "ultimateAlpr::UltAlprDetector::newObj()"
file: "source\ultimate_alpr_detector.cxx"
line: "56"
message: Operation Failed (COMPV_ERROR_CODE_E_THIRD_PARTY_LIB) ->
***[COMPV ERROR]: function: "ultimateAlpr::UltAlprDetector::newObj()"
file: "source\ultimate_alpr_detector.cxx"
line: "62"
message: [UltAlprDetector] Failed to create OpenVINO detector/classifier. Fallback to Tensorflow detector/classifier.

**Comment by DoubangoTelecom** [comment]
This issue is fixed. Check https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B#gpu-acceleration-openvino-myriad. Your drivers are correctly installed, just update the code and it should work. We'll close this ticket when a full release (v.3.4) is out.
