### ISSUE TITLE
 Assertion `__ULTALPR_SDK_b_ret' failed. Aborted in Pi3

### ISSUE THREAD

**Issue by scizors** [DoubangoTelecom/ultimateALPR-SDK#136]
Hi,
 I am using pi3 and raspbian os I also copied the image to the folder.
 my image is "1.jpg"

pi@raspberrypi:~/ultimateALPR-SDK/samples/c++/recognizer $ ./recognizer --image 1.jpg
*[ULTALPR_SDK INFO]: Starting recognizer...
*[COMPV INFO]: [UltAlprSdkEngine] Call: init
*[COMPV INFO]: [UltAlprSdkEngine] jsonConfig: {"debug_level": "info","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","num_threads": -1,"gpgpu_enabled": true,"klass_vcr_gamma": 1.5,"detect_roi": [0, 0, 0, 0],"detect_minscore": 0.1,"car_noplate_detect_min_score": 0.8,"pyramidal_search_enabled": true,"pyramidal_search_sensitivity": 1.0,"pyramidal_search_minscore": 0.3,"pyramidal_search_min_image_size_inpixels": 800,"recogn_minscore": 0.3,"recogn_score_type": "min","charset": "latin","recogn_rectify_enabled": false,"car_noplate_detect_enabled": false,"ienv_enabled": false,"openvino_enabled": true,"openvino_device": "CPU","klass_lpci_enabled": false,"klass_vcr_enabled": false,"klass_vmmr_enabled": false,"klass_vbsr_enabled": false}
*[COMPV INFO]: [UltAlprSdkEngine] **** Copyright (C) 2011-2021 Doubango Telecom <https://www.doubango.org> ****
ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK> version 3.3.0

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #4
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] H: 'BCM2835', S: '***', M: 'Raspberry Pi 3 Model B Rev 1.2', MN: 'ARMv7 Processor rev 4 (v7l)'
*[COMPV INFO]: [CompVBase] CPU features: [arm];neon;neon_fma;vfpv3;vfpv4;
*[COMPV INFO]: [CompVBase] CPU cores: #4
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #0B, size :#0KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #872GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: AArch32
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] Code built with option /arch:NEON
*[COMPV INFO]: [CompVBase] OS name: Raspberry Pi
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #32
*[COMPV INFO]: [CompVBase] Best alignment: #32
*[COMPV INFO]: [CompVBase] Heap limit: #262144KB (#256MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=0,set=useless, threadId:0x758a7400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=1,set=useless, threadId:0x750a6400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=2,set=useless, threadId:0x748a5400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #4 threads/#4 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=3,set=useless, threadId:0x740a4400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateBase/lib/source/ultimate_base_engine.cxx' in function 'init' starting at line #75: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [libOpenCL.so]
*[COMPV INFO]: [UltBaseOpenCL] Failed to load [libOpenCL.so]
*[COMPV INFO]: [UltOcrEngine] Tensorflow version: 1.12.3
*[COMPV INFO]: [UltAlprSdkEnginePrivate] **** Copyright (C) 2011-2021 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK>
without the rights to include the SDK in any form of commercial product.
*[COMPV INFO]: [UltAlprSdkEnginePrivate] IC took 0 millis
*[COMPV INFO]: [CompVCpu] Enabling asm code
*[COMPV INFO]: [CompVCpu] Enabling intrinsic code
*[COMPV INFO]: [UltAlprSdkEnginePrivate] pysearch_sensitivity(1.000000) >= 1.0, using the most accurate model possible. More info at https://www.doubango.org/SDKs/anpr/docs/Improving_the_accuracy.html#golden-number.
*[COMPV INFO]: [UltAlprSdkEnginePrivate] recogn_tf_num_threads: 4
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateOCR/lib/source/ultimate_ocr_charset.cxx" 
line: "58" 
message: [UltOcrCharset] Charset file at C:/Projects/GitHub/ultimate/ultimateALPR/charset_anpr_latin_size=37.txt -> /home/pi/ultimateALPR-SDK/samples/c++/recognizer/charset_anpr_latin_size=37.txt doesn't exist
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateOCR/lib/source/ultimate_ocr_recognizer.cxx" 
line: "637" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateALPR/lib/source/ultimate_alpr_recognizer.cxx" 
line: "176" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_recognizer.cxx" 
line: "243" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> Failed to create Alpr recognizer
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
line: "342" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: Drawing module deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [Thread] Thread with id=0x758a7400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x758a7400) - EXIT
*[COMPV INFO]: Thread with id=0x758a7400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x758a7400 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x750a6400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x750a6400) - EXIT
*[COMPV INFO]: Thread with id=0x750a6400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x750a6400 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x748a5400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x748a5400) - EXIT
*[COMPV INFO]: Thread with id=0x748a5400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x748a5400 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x740a4400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x740a4400) - EXIT
*[COMPV INFO]: Thread with id=0x740a4400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x740a4400 destroyed***
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
line: "131" 
message: [UltAlprSdkEngine] Failed to initialize the engine
recognizer: recognizer.cxx:242: int main(int, char**): Assertion `__ULTALPR_SDK_b_ret' failed.
Aborted

**Comment by DoubangoTelecom** [comment]
Add `--assets ../../../assets` to the command as explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#examples

**Comment by scizors** [comment]
@DoubangoTelecom  thanks a lot
 ./recognizer --image 1.jpg --assets ../../../assets
 works good
