### ISSUE TITLE
Rectify Segmentation Fault

### ISSUE THREAD

**Issue by dididudikov** [DoubangoTelecom/ultimateALPR-SDK#143]
I'm using raspberry pi 4 model 4Gb. and using latest Raspberry pi OS. Compiling sample successful. running benchmark with rectify enable will raise Segmentation Fault.

**Comment by dididudikov** [comment]
[segmentationFault.txt](https://github.com/DoubangoTelecom/ultimateALPR-SDK/files/6328073/segmentationFault.txt)

this is the full log

**Comment by DoubangoTelecom** [comment]
could you share a sample image reproducing the issue?

**Comment by DoubangoTelecom** [comment]
> could you share a sample image reproducing the issue?

Never mind, we have managed to reproduce the crash

**Comment by DoubangoTelecom** [comment]
Disabling assembler code causing the crash: https://github.com/DoubangoTelecom/compv/commit/a028b1dbf52f09bb7e9914ca51da847bd8ab67f1
Will be fixed in v3.3.2
