### ISSUE TITLE
What vehicle make models do you support

### ISSUE THREAD

**Issue by dominikberta** [DoubangoTelecom/ultimateALPR-SDK#147]
I want to ask what vehicle models do you actually support? On the website there is that all make models are in this file: https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/assets/models/ultimateALPR-SDK_klass_labels_vmmr.txt.doubango

But I do not know how to open it as a normal text - what is the encoding. Can you please write me the full list of vehicle models? Thank you!

**Comment by DoubangoTelecom** [comment]
[vmmr-list.txt](https://github.com/DoubangoTelecom/ultimateALPR-SDK/files/6423171/vmmr-list.txt)

**Comment by DoubangoTelecom** [comment]
[vmmr.txt](https://github.com/DoubangoTelecom/ultimateALPR-SDK/files/8486364/vmmr.txt)

**Comment by jheaff1** [comment]
Your [website](https://www.doubango.org/SDKs/anpr/docs/Features.html#supported-makes) says that the list is updated every 6 months, but the [SDK_klass_labels_vmmr.txt.doubango](https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/assets/models/ultimateALPR-SDK_klass_labels_vmmr.txt.doubango) file is 2 years old. When do you expect to update the list?
