### ISSUE TITLE
disable compv info

### ISSUE THREAD

**Issue by scizors** [DoubangoTelecom/ultimateALPR-SDK#148]
Hi,
 At the moment I am testing the trial version ultimateALPR-SDK in my ARM machine with German number plates C++ solution. 
 I am using snapshot of the car numberplates inside Germany
 As I am getting with most of the number plates output as 
 
` *[ULTALPR_SDK INFO]: result: {"duration":4353,"frame_id":0}`

 
 I would like to know few things
 1. Differnce between the trial version and commerical paid version in terms of accuracy (apart from last character in the number plate is *)
 2. As I see there is  *[COMPV INFO]: and *[ULTALPR_SDK INFO]:  is it possible to disable *[COMPV INFO]: in my trial version just for testing purpose.

**Comment by scizors** [comment]
Hi, 

 Thank you for the info
 1.
![2021-05-06 lade_brightness_add_25_resize 0](https://user-images.githubusercontent.com/44981587/117622353-daca2100-b172-11eb-92bb-af56e52ec428.jpg)

 
 
 2. I have changed to "warn" as shown below 
 
` [UltAlprSdkEngine] jsonConfig: {"debug_level": "warn","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","num_threads": -1,"gpgpu_enabled": true,"klass_vcr_gamma": 1.5,"detect_roi": [0, 0, 0, 0],"detect_minscore": 0.1,"car_noplate_detect_min_score": 0.8,"pyramidal_search_enabled": true,"pyramidal_search_sensitivity": 1.0,"pyramidal_search_minscore": 0.3,"pyramidal_search_min_image_size_inpixels": 800,"recogn_minscore": 0.3,"recogn_score_type": "min","assets_folder": "../../../assets","charset": "latin","recogn_rectify_enabled": false,"car_noplate_detect_enabled": false,"ienv_enabled": false,"openvino_enabled": true,"openvino_device": "CPU","klass_lpci_enabled": false,"klass_vcr_enabled": false,"klass_vmmr_enabled": false,"klass_vbsr_enabled": false}`

Still I am seeing *[COMPV INFO]: is there any waw to diable?

**Comment by DoubangoTelecom** [comment]
- no, some logs cannot be disabled
- set "recogn_rectify_enabled" to true. More at https://www.doubango.org/SDKs/anpr/docs/Rectification_layer.html.

**Comment by DoubangoTelecom** [comment]
I have checked with https://www.doubango.org/webapps/alpr/ and it fails to recognize the plate. These kind of images should be easily recognized. I'm reopening this ticket and we'll check. If you can share with us more images to use in our training set then it'll help us improve the algo.
