### ISSUE TITLE
How to Run using python

### ISSUE THREAD

**Issue by AbhijeetGhosh** [DoubangoTelecom/ultimateALPR-SDK#15]
How do we use this SDK in python. Just need a hint that's all. Thanks!

**Comment by DoubangoTelecom** [comment]
Hello,

For information we have released the Python documentation in version 2.11.0. Recognizer sample in python: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer <https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer>

Regards,
