### ISSUE TITLE
Taiwan license plate

### ISSUE THREAD

**Issue by Avadesign-David** [DoubangoTelecom/ultimateALPR-SDK#154]
Since the accuracy is not enough for Taiwan license plate format. Can we provide some image data(few hundred) for training? 
And perhaps we can provide the characters(Taiwan license plate used) sample if needed.

**Comment by DoubangoTelecom** [comment]
Duplicate of #151

**Comment by DoubangoTelecom** [comment]
Fixed by v3.7.0
