### ISSUE TITLE
Unknown process state

### ISSUE THREAD

**Issue by dominikberta** [DoubangoTelecom/ultimateALPR-SDK#157]
Hello,

I am using your ALPR SDK in application and it gives me this error:

`--------- beginning of crash
06-24 17:14:51.310 23328 23328 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 23328 (com.rmz), pid 23328 (com.rmz)

06-24 17:14:51.412 22378 22378 E crash_dump64: unknown process state: t

06-24 17:14:51.502 22378 22378 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-24 17:14:51.502 22378 22378 F DEBUG   : Build fingerprint: 'samsung/gtactive3eea/gtactive3:10/QP1A.190711.020/T575XXU2AUA4:user/release-keys'
06-24 17:14:51.502 22378 22378 F DEBUG   : Revision: '4'
06-24 17:14:51.502 22378 22378 F DEBUG   : ABI: 'arm64'
06-24 17:14:51.513 22378 22378 F DEBUG   : Timestamp: 2021-06-24 17:14:51+0200
06-24 17:14:51.514 22378 22378 F DEBUG   : pid: 23328, tid: 23328, name: com.rmz  >>> com.rmz <<<
06-24 17:14:51.514 22378 22378 F DEBUG   : uid: 10426
06-24 17:14:51.514 22378 22378 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
06-24 17:14:51.514 22378 22378 F DEBUG   : Cause: null pointer dereference

06-24 17:14:51.514 22378 22378 F DEBUG   :     x0 0000007380751ea8  x1  00000072f38ee5e8  x2  0000000000000000  x3 00000072ead74160
06-24 17:14:51.514 22378 22378 F DEBUG   :     x4 0000007270cf4c70  x5  0000007270cf4ff0  x6  0000007270cf4f10  x7 0000000000000000
06-24 17:14:51.514 22378 22378 F DEBUG   :     x8 00000000ffffff7f  x9  0000000000000000  x10 00000000ffffff7a  x11 0000000000000000
06-24 17:14:51.514 22378 22378 F DEBUG   :     x12 0000000000000000  x13 0000000060d4a16b  x14 00121f9935e2264e  x15 0000517f94eb5468
06-24 17:14:51.514 22378 22378 F DEBUG   :     x16 00000072e66df860  x17 00000072e64c53d4  x18 0000000000000578  x19 0000000000000000
06-24 17:14:51.514 22378 22378 F DEBUG   :     x20 0000007270cf4f10  x21 0000007380751ea8  x22 0000007270cf4c70  x23 0000007270cf4ff0
06-24 17:14:51.514 22378 22378 F DEBUG   :     x24 00000072f38ee5e8  x25 0000007270cf4f80  x26 0000000000000070  x27 000000728cdab878
06-24 17:14:51.514 22378 22378 F DEBUG   :     x28 0000007270cef480  x29 0000007fe3b0fd30
06-24 17:14:51.514 22378 22378 F DEBUG   :     sp 0000007fe3b0fbe0  lr  00000072e64b8b00  pc  00000072e64c5448
06-24 17:14:51.516 22378 22378 F DEBUG   :

06-24 17:14:51.516 22378 22378 F DEBUG   : backtrace:
06-24 17:14:51.517 22378 22378 F DEBUG   :       #00 pc 00000000000e3448 /data/app/com.rmz-nTUP3uJz_-Oxoaf6MjK0kg==/lib/arm64/libtensorflowlite.so (_ZN6tflite3ops7builtin4conv13EvalQuantizedILNS2_10KernelTypeE1EEEvP13TfLiteContextP10TfLiteNodeP16TfLiteConvParamsPNS2_6OpDataEPK12TfLiteTensorSF_SF_PSD_SG_+116)
06-24 17:14:51.517 22378 22378 F DEBUG   :       #01 pc 00000000000d6afc /data/app/com.rmz-nTUP3uJz_-Oxoaf6MjK0kg==/lib/arm64/libtensorflowlite.so (_ZN6tflite3ops7builtin4conv8EvalImplILNS2_10KernelTypeE1EL10TfLiteType3EEE12TfLiteStatusP13TfLiteContextP10TfLiteNode+404)
06-24 17:14:51.517 22378 22378 F DEBUG   :       #02 pc 00000000000d6910 /data/app/com.rmz-nTUP3uJz_-Oxoaf6MjK0kg==/lib/arm64/libtensorflowlite.so (_ZN6tflite3ops7builtin4conv4EvalILNS2_10KernelTypeE1EEE12TfLiteStatusP13TfLiteContextP10TfLiteNode+152)
06-24 17:14:51.517 22378 22378 F DEBUG   :       #03 pc 0000000000245104 /data/app/com.rmz-nTUP3uJz_-Oxoaf6MjK0kg==/lib/arm64/libtensorflowlite.so (tflite::Subgraph::Invoke()+1048)
06-24 17:14:51.517 22378 22378 F DEBUG   :       #04 pc 0000000000248f9c /data/app/com.rmz-nTUP3uJz_-Oxoaf6MjK0kg==/lib/arm64/libtensorflowlite.so (tflite::Interpreter::Invoke()+96)
06-24 17:14:51.517 22378 22378 F DEBUG   :       #05 pc 00000000007a51b8 /data/app/com.rmz-nTUP3uJz_-Oxoaf6MjK0kg==/lib/arm64/libultimateALPR_SDK.so`

App is crashing and according to backtrace, the error is located in libtensorflowlite.so and libultimateALPR_SDK.so. Is there any error on your side or am I calling some function (for example UltAlprSdkEngine.deInit() or UltAlprSdkEngine.init()) wrong? 

It happens when I am reinitializing library, because I need to change processing from parallel to senquential for one functionality, so I am calling UltAlprSdkEngine.deInit(); and then  UltAlprSdkEngine.init();. After reinitialization I am calling UltAlprSdkEngine.process() multiple times (30x). The app is crashing with this error but not everytime this function is called. It does not crash shortly after reinitialization, maybe it crash when I am again reinitializing and changing from sequential processing to parallel on the end of function. But as I said it doesn't happen every time I call the function.

Thank you!

**Comment by DoubangoTelecom** [comment]
Please attach full logs. We have no idea about your device, sdk version... Also add code to reproduce the issue.
