### ISSUE TITLE
Running in a Linux x86

### ISSUE THREAD

**Issue by ggmac23** [DoubangoTelecom/ultimateALPR-SDK#16]
Hi, I wanted to know if you can run your sdk on my linux machine, in binaries directory I found only android and raspberry project.

**Comment by DoubangoTelecom** [comment]
Linux is supported. Our cloud (https://www.doubango.org/webapps/alpr/) uses Ubuntu 18 but for now only Android and Raspberry Pi binaries are public.

**Comment by DoubangoTelecom** [comment]
Version 2.7.0 makes Linux x86_64 binaries public:
- C++ samples: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B
