### ISSUE TITLE
Frame prefix for lpr and callback

### ISSUE THREAD

**Issue by VizDock** [DoubangoTelecom/ultimateALPR-SDK#164]
Hi
This is just inquiry about possible improvement.
When picture is added to lpr, and callback notifies about result, frame number is important to associate result with initial request.
It would be nice if its possible to set prefix for frame, so that if I have multiple cameras streaming their rtsp video, I could differentiate callback result of each camera.
Now, at least what I know, it is not possible

**Comment by DoubangoTelecom** [comment]
We have FIFO mechanism (First In First Out) for the parallel mode. Do something like this:
```
static mutex;
static map<uint64_t, string>
static uint64_t counter = 0;
```

```
on_new_frame(void* frame, string camera_name) {
    mutex.lock();
    map[++counter] = camera_name; // here you are linking the camera to a frame identifier
    process(frame, ....);
    mutex.unlock();
}
```

```
alpr_callback(uint64_t frame_id) { // onNewResult(result)
    mutex.lock();
    string camera_name = map[frame_id]; // retrieve the camera identifier from the frame identifier
    map.erase(frame_id);
    mutex.unlock();
}
```

**Comment by DoubangoTelecom** [comment]
To save memory you may use "int camera_id" instead of "string camera_name" to uniquely identify cameras

**Comment by neseih** [comment]
> We have FIFO mechanism (First In First Out) for the parallel mode. Do something like this:
> 
> ```
> static mutex;
> static map<uint64_t, string>
> static uint64_t counter = 0;
> ```
> 
>  ```
> on_new_frame(void* frame, string camera_name) {
>     mutex.lock();
>     map[++counter] = camera_name; // here you are linking the camera to a frame identifier
>     process(frame, ....);
>     mutex.unlock();
> }
> ```
> 
>  ```
> alpr_callback(uint64_t frame_id) { // onNewResult(result)
>     mutex.lock();
>     string camera_name = map[frame_id]; // retrieve the camera identifier from the frame identifier
>     map.erase(frame_id);
>     mutex.unlock();
> }
> ```

As far as I remember, alpr_callback is not called always (e.g. no objects in first pass).
Won‘t this create a „memory leak“ as „no object frames“ in map are never erased?

**Comment by DoubangoTelecom** [comment]
> > We have FIFO mechanism (First In First Out) for the parallel mode. Do something like this:
> > ```
> > static mutex;
> > static map<uint64_t, string>
> > static uint64_t counter = 0;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > on_new_frame(void* frame, string camera_name) {
> >    mutex.lock();
> >    map[++counter] = camera_name; // here you are linking the camera to a frame identifier
> >    process(frame, ....);
> >    mutex.unlock();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > alpr_callback(uint64_t frame_id) { // onNewResult(result)
> >    mutex.lock();
> >    string camera_name = map[frame_id]; // retrieve the camera identifier from the frame identifier
> >    map.erase(frame_id);
> >    mutex.unlock();
> > }
> > ```
> 
> As far as I remember, alpr_callback is not called always (e.g. no objects in first pass).
> Won‘t this create a „memory leak“ as „no object frames“ in map are never erased?

This is pseudo code written is 5 sec. Off course you have to to adapt it.
If there is no plate the process() function will return result->numPlates() == 0, in this case erase the entry without waiting the callback. I'll edit the pseudo code.

**Comment by DoubangoTelecom** [comment]
Edited the pseudo code

**Comment by neseih** [comment]
Thx. This could help others as well to avoid some surprises 😀

**Comment by VizDock** [comment]
Thanks guys
