### ISSUE TITLE
RTSP Source video Python

### ISSUE THREAD

**Issue by Thib390** [DoubangoTelecom/ultimateALPR-SDK#165]
Hi,

I use python extension on linux x86. I add rtsp source code with opencv using YUV format:
ultimateAlprSdk.ULTALPR_SDK_IMAGE_TYPE_YUV420P

I simply add rtsp from opencv and convert grabbed images in PIL image and then convert to YUV format.

Resulting in Process:

*[COMPV INFO]: /!\ Code in file '/home/ultimate/compv/base/compv_mem.cxx' in function 'CompVMemCopy_C' starting at line #985: Not optimized -> No SIMD implementation found. On ARM consider http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka13544.html
[PythonRecognizer] Process: OK -> {"duration":425,"frame_id":0}

**Comment by DoubangoTelecom** [comment]
Must be BGR instead of YUV. Check https://www.doubango.org/SDKs/anpr/docs/Getting_started.html#opencv
