### ISSUE TITLE
prepare.sh gives Bus error : jetson nano

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#172]
Im getting bus error on jetson nano :-

```
 ./prepare.sh 
./prepare.sh: line 13:  8133 Bus error               sudo ./trt_optimizer --assets ../../../assets

```

- NVIDIA Jetson Nano (Developer Kit Version)
   * Jetpack 4.5.1 [L4T 32.5.1]
   * NV Power Mode: MAXN - Type: 0
   * jetson_stats.service: active
 - Libraries:
   * CUDA: 10.2.89
   * cuDNN: 8.0.0.180
   * TensorRT: 7.1.3.0
   * Visionworks: 1.6.0.501
   * OpenCV: 4.5.2 compiled CUDA: YES
   * VPI: ii libnvvpi1 1.0.15 arm64 NVIDIA Vision Programming Interface library
   * Vulkan: 1.2.70

TEGRASTATS :-
`RAM 800/1978MB (lfb 40x4MB) SWAP 0/5085MB (cached 0MB) CPU [0%@2014,1%@2014,0%@2014,0%@2014] EMC_FREQ 0% GR3D_FREQ 0% PLL@42C CPU@43.5C PMIC@100C GPU@43.5C AO@52C thermal@43.5C`
 

I just changed MAX-N to 1, still same bus error

**Comment by DoubangoTelecom** [comment]
As explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md, use JetPack 4.4.1, that's the only version we fully tested. That was the latest version when we released the code.

**Comment by msavara** [comment]
> As explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md, use JetPack 4.4.1, that's the only version we fully tested. That was the latest version when we released the code.

But times have changed. All jetson nano that you already buy come with jetpack 4.6 and higher pre-installed and downgrade is not possible.

**Comment by DoubangoTelecom** [comment]
> > As explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md, use JetPack 4.4.1, that's the only version we fully tested. That was the latest version when we released the code.
> 
> But times have changed. All jetson nano that you already buy come with jetpack 4.6 and higher pre-installed and downgrade is not possible.

Jetson doesn't come with any pre-installed OS. So, I don't see what you meant.

**Comment by msavara** [comment]
> > > As explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md, use JetPack 4.4.1, that's the only version we fully tested. That was the latest version when we released the code.
> > 
> > 
> > But times have changed. All jetson nano that you already buy come with jetpack 4.6 and higher pre-installed and downgrade is not possible.
> 
> Jetson doesn't come with any pre-installed OS. So, I don't see what you meant.

We bought it on amazon.de for the second time and both came with preinstalled OS from nvidia and were only compatible with 4.6 jetpack. do you have any good power supply for jetson nano from where you buy?

**Comment by DoubangoTelecom** [comment]
> > > > As explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md, use JetPack 4.4.1, that's the only version we fully tested. That was the latest version when we released the code.
> > > 
> > > 
> > > But times have changed. All jetson nano that you already buy come with jetpack 4.6 and higher pre-installed and downgrade is not possible.
> > 
> > 
> > Jetson doesn't come with any pre-installed OS. So, I don't see what you meant.
> 
> We bought it on amazon.de for the second time and both came with preinstalled OS from nvidia and were only compatible with 4.6 jetpack. do you have any good power supply for jetson nano from where you buy?

You probably bought it from a reseller that is packaging it and selling it more. Stock Nano comes alone without SD card or power supply. Anyways, the OS is on an SD card, you can replace the SD card or override it, no need to downgrade. I don't understand the point of being stuck because your Nano has 4.6. I would understand if you tell me your app requires features in 4.6

**Comment by msavara** [comment]
> > > > > As explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md, use JetPack 4.4.1, that's the only version we fully tested. That was the latest version when we released the code.
> > > > 
> > > > 
> > > > But times have changed. All jetson nano that you already buy come with jetpack 4.6 and higher pre-installed and downgrade is not possible.
> > > 
> > > 
> > > Jetson doesn't come with any pre-installed OS. So, I don't see what you meant.
> > 
> > 
> > We bought it on amazon.de for the second time and both came with preinstalled OS from nvidia and were only compatible with 4.6 jetpack. do you have any good power supply for jetson nano from where you buy?
> 
> You probably bought it from a reseller that is packaging it and selling it more. Stock Nano comes alone without SD card or power supply. Anyways, the OS is on an SD card, you can replace the SD card or override it, no need to downgrade. I don't understand the point of being stuck because your Nano has 4.6. I would understand if you tell me your app requires features in 4.6

Yes you were right. We bought the jetson nano from a reseller and there was a newer OS. We managed to do a downgrade using sdkmanager --archivedversions
