### ISSUE TITLE
prepare.sh always gets killed on last line

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#173]
I'm on Jetpack 4.4.1, with MAX-N = 1 , Jetson 2GB RAM

The device shows 100% RAM & CPU before getting killed
```
2021-08-07 20:58:36.116312: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-08-07 20:58:38.953528: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
./prepare.sh: line 13: 22743 Killed                  sudo ./trt_optimizer --assets ../../../assets
```

**Comment by DoubangoTelecom** [comment]
Don't open new threads for the same issue.

**Comment by rsingh2083** [comment]
This is not same issue. Its crashing with Jetpack 4.4.1 also, please read again

**Comment by DoubangoTelecom** [comment]
Models generation is CPU and memory intensive. Do it on a nano 8G then move the models to the 4G devices. Use binaries under jetson folder instead of jetson_tftrt

**Comment by rsingh2083** [comment]
Can you upload/share tfTRT model for JetPack 4.4.1 ?

**Comment by DoubangoTelecom** [comment]
> Can you upload/share tfTRT model for JetPack 4.4.1 ?

https://www.doubango.org/SDKs/anpr/optimized.zip -> https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/assets/models.tensorrt/optimized

I have tried to rebuild the models using the latest version and it works fine. So, no regression.

**Comment by rsingh2083** [comment]
I download and copied the optimized folders content at respective location but while running 
`
LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./recognizer     --image ../../../assets/images/lic_us_1280x720.jpg     --assets ../../../assets     --charset latin     --parallel false     --rectify true`

Im getting this error :-


```
***[COMPV ERROR]: function: "optimizedPath()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
line: "228" 
message: [UltAlprSdkTRT] Plan file (../../../assets/models.tensorrt/optimized/ultimateALPR-SDK_detect_main.desktop.model.tensorrt.plan.doubango-3.3) doesn't exist. You must generate the plans as explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md#building-optimized-models
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
line: "257" 
message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) -> 
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
line: "131" 
message: [UltAlprSdkEngine] Failed to initialize the engine
****[ULTALPR_SDK FATAL]: function: "main()" 
file: "/home/ultimate/ultimateALPR/SDK_dist/samples/c++/recognizer/recognizer.cxx" 
line: "242" 
message: Assertion failed!
Aborted (core dumped)

```

**Comment by DoubangoTelecom** [comment]
> I download and copied the optimized folders content at respective location but while running
> ` LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./recognizer --image ../../../assets/images/lic_us_1280x720.jpg --assets ../../../assets --charset latin --parallel false --rectify true`
> 
> Im getting this error :-
> 
> ```
> ***[COMPV ERROR]: function: "optimizedPath()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
> line: "228" 
> message: [UltAlprSdkTRT] Plan file (../../../assets/models.tensorrt/optimized/ultimateALPR-SDK_detect_main.desktop.model.tensorrt.plan.doubango-3.3) doesn't exist. You must generate the plans as explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md#building-optimized-models
> ***[COMPV ERROR]: function: "init()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
> line: "257" 
> message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) -> 
> ***[COMPV ERROR]: function: "init()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
> line: "131" 
> message: [UltAlprSdkEngine] Failed to initialize the engine
> ****[ULTALPR_SDK FATAL]: function: "main()" 
> file: "/home/ultimate/ultimateALPR/SDK_dist/samples/c++/recognizer/recognizer.cxx" 
> line: "242" 
> message: Assertion failed!
> Aborted (core dumped)
> ```
> 
> I dont have this file, can you please share this :- ` ultimateALPR-SDK_detect_main.desktop.model.tensorrt.plan.doubango-3.3`

I have to regenerate all the models using a newer version. Don't have access to a device, and will not for a long time. Rename ultimateALPR-SDK_detect_main.desktop.model.tensorrt.plan.doubango-3.1 in the zip to ultimateALPR-SDK_detect_main.desktop.model.tensorrt.plan.doubango-3.1, do the same for all other files. You will be using old versions (less accurate). You'll have to generate the models by yourself if you want to use newest versions. That said, we **don't recommend** using jetson_tftrt on a 2GB nano.

**Comment by rsingh2083** [comment]
Ive fixed this issue.
Can you help me with this issue --
https://github.com/DoubangoTelecom/ultimateALPR-SDK/issues/156#issuecomment-894826269

**Comment by DoubangoTelecom** [comment]
Duplicate of #172

**Comment by DoubangoTelecom** [comment]
> Ive fixed this issue.
> Can you help me with this issue --
> [#156 (comment)](https://github.com/DoubangoTelecom/ultimateALPR-SDK/issues/156#issuecomment-894826269)

You said yourself you have 100% memory usage when trying to generate models on a 2GB nano. An we already responded that a 2G memory is not enough to build the models and we suggested using a 4GB nano to generate the models and moving them to your 2GB devices. What help do you still want?
