### ISSUE TITLE
Windows 10 pro - not working demo

### ISSUE THREAD

**Issue by vlkc** [DoubangoTelecom/ultimateALPR-SDK#175]
Hello, where to dig to find why it's not working?

![Capture](https://user-images.githubusercontent.com/76711995/128611218-cfcae4f9-0c5c-4b06-82c0-321f7a33d370.PNG)

**Comment by DoubangoTelecom** [comment]
Check dependencies -> https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#dependencies-debugging

**Comment by vlkc** [comment]
Help me identify please. 

[recognizer.zip](https://github.com/DoubangoTelecom/ultimateALPR-SDK/files/6950480/recognizer.zip)

**Comment by DoubangoTelecom** [comment]
You have to run it on your pc.

**Comment by vlkc** [comment]
I did, There is export info from my PC in archive

**Comment by DoubangoTelecom** [comment]
> I did, There is export info from my PC in archive

Did you install [Microsoft Visual C++ 2015 Redistributable(x64) - 14.0.24123](https://www.microsoft.com/en-us/download/details.aspx?id=52685) as explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Dependencies.md#known-issues
