### ISSUE TITLE
How can I view the number plates live over the video ?

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#176]
Hi,
In this link you have shown number plates live over video.
https://www.youtube.com/watch?v=jozcaDMMgVU

What I tried & is working successfully on image :- 
```
#include <iostream>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
using namespace cv;
using namespace std;

int main(int argc, char** argv)
{
    // Reading the Image
    Mat image = imread("lic_us_1280x720.jpg", IMREAD_COLOR);
        if (!image.data) {
        std::cout << "Could not open or "
                  << "find the image\n";
        return 0;
    }
  
    // Top Left Coordinates
    Point p1(820.0173,343.1933);
      // Bottom Right Coordinates
    Point p2(941.6364,406.0498);
  
    int thickness = 2;
  
    // Drawing the Rectangle
    rectangle(image, p1, p2,
              Scalar(255, 0, 0),
              thickness, LINE_8);
    cv::putText(image, //target image
            "3PEDLM4", //text
            cv::Point(820, 330), //top-left position
            cv::FONT_HERSHEY_DUPLEX,
            1.0,
            CV_RGB(118, 185, 0), //font color
            2);

    // Show our image inside a window
    imshow("Output", image);
    waitKey(0);
  
    return 0;
}
```

How can we do the same over a video?

**Comment by rsingh2083** [comment]
With all due respect this ticket is about displaying the number plate result real time over a video. Just like you have in this
video :- https://www.youtube.com/watch?v=jozcaDMMgVU

**Comment by DoubangoTelecom** [comment]
> With all due respect this ticket is about displaying the number plate result real time over a video. Just like you have in this
> video :- https://www.youtube.com/watch?v=jozcaDMMgVU

This is a question for OpenCV group. We are using our own Drawing code from CompV (https://github.com/DoubangoTelecom/compv/tree/master/drawing). This question is out of scoop.
