### ISSUE TITLE
Simple code to run ALPR on video file ?

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#177]
Can you guys please share a simple code to run your ALPR in C++ on a video file ?
Its really painful for novices to get a hang of the things. 
Id be very grateful.

**Comment by DoubangoTelecom** [comment]
Sorry but uf you keep opening tickets you'll be banned.

**Comment by DoubangoTelecom** [comment]
Duplicate of #176
