### ISSUE TITLE
Unable to compile thie video C++ code

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#178]
Im trying to compile this code :-

`desktop:~/ultimateALPR-SDK/binaries/jetson_tftrt/aarch64$ g++ -std=c++11 -O3 test.cpp  -o out `pkg-config --cflags --libs opencv4``

CODE
```
#include "opencv2/opencv.hpp"
#include "iostream"
#include "ultimateALPR-SDK-API-PUBLIC.h"


static const char* __jsonConfig =
"{"
"\"debug_level\": \"info\","
"\"debug_write_input_image_enabled\": false,"
"\"debug_internal_data_path\": \".\","
"\"num_threads\": -1,"
"\"klass_vcr_gamma\": 1.5,"
"\"detect_roi\": [0, 0, 0, 0],"
"\"detect_minscore\": 0.1,"
"\"car_noplate_detect_min_score\": 0.8,"
"\"pyramidal_search_enabled\": true,"
"\"pyramidal_search_sensitivity\": 1.0,"
"\"pyramidal_search_minscore\": 0.3,"
"\"pyramidal_search_min_image_size_inpixels\": 800,"
"\"recogn_minscore\": 0.3,"
"\"recogn_score_type\": \"min\","
"\"recogn_rectify_enabled\": false,"
"\"assets_folder\": \"/root/ultimateALPR-SDK/assets\","
"\"charset\": \"latin\","
"\"car_noplate_detect_enabled\": false,"
"\"gpgpu_enabled\": false,"
"\"ienv_enabled\": false,"
"\"openvino_enabled\": false,"
"\"klass_lpci_enabled\": false,"
"\"klass_vcr_enabled\": false,"
"\"klass_vmmr_enabled\": false,"
"\"klass_vbsr_enabled\": false"
"}";

using namespace ultimateAlprSdk;

int main() {
        cv::Mat frame;
        cv::VideoCapture cap("video.mp4");

        if (!cap.isOpened()) {
                std::cout << "Cannot open the video" << std::endl;
                return -1;
        }

        UltAlprSdkResult result;
        std::string jsonConfig = __jsonConfig;
        ULTALPR_SDK_ASSERT((result = UltAlprSdkEngine::init(jsonConfig.c_str())).isOK());

        while(1) {
                cap >> frame;

                if (frame.empty())
                        break;

                ULTALPR_SDK_ASSERT((result = UltAlprSdkEngine::process(
                        ULTALPR_SDK_IMAGE_TYPE_YUV420P,
                        frame.ptr(),
                        frame.size().width,
                        frame.size().height
                )).isOK());

                const std::string& json = result.json();
                if (!json.empty())
                        ULTALPR_SDK_PRINT_INFO("result: %s", json.c_str());
        }

        ULTALPR_SDK_ASSERT((result = UltAlprSdkEngine::deInit()).isOK());

        return 0;
}
```
But Im unable to compile it at all , ERROR :----

/tmp/ccZowF1t.o: In function `main':
test.cpp:(.text.startup+0x33c): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::UltAlprSdkResult()'
test.cpp:(.text.startup+0x37c): undefined reference to `ultimateAlprSdk::UltAlprSdkEngine::init(char const*, ultimateAlprSdk::UltAlprSdkParallelDeliveryCallback const*)'
test.cpp:(.text.startup+0x388): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::operatorAssign(ultimateAlprSdk::UltAlprSdkResult const&)'
test.cpp:(.text.startup+0x394): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::~UltAlprSdkResult()'
test.cpp:(.text.startup+0x3ec): undefined reference to `ultimateAlprSdk::UltAlprSdkEngine::deInit()'
test.cpp:(.text.startup+0x3f8): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::operatorAssign(ultimateAlprSdk::UltAlprSdkResult const&)'
test.cpp:(.text.startup+0x404): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::~UltAlprSdkResult()'
test.cpp:(.text.startup+0x42c): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::~UltAlprSdkResult()'
test.cpp:(.text.startup+0x450): undefined reference to `ultimateAlprSdk::UltAlprSdkEngine::process(ultimateAlprSdk::ULTALPR_SDK_IMAGE_TYPE, void const*, unsigned long, unsigned long, unsigned long, int)'
test.cpp:(.text.startup+0x45c): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::operatorAssign(ultimateAlprSdk::UltAlprSdkResult const&)'
test.cpp:(.text.startup+0x468): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::~UltAlprSdkResult()'
test.cpp:(.text.startup+0x594): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::~UltAlprSdkResult()'
test.cpp:(.text.startup+0x5b8): undefined reference to `ultimateAlprSdk::UltAlprSdkResult::~UltAlprSdkResult()'
collect2: error: ld returned 1 exit status

**Comment by DoubangoTelecom** [comment]
Add `-lultimate_alpr-sdk` as explained in the documentation.

**Comment by DoubangoTelecom** [comment]
Duplicate of #176

**Comment by rsingh2083** [comment]
> Add `-lultimate_alpr-sdk` as explained in the documentation.

Still same problem :-
```
ns-16g@ns16g-desktop:~/ultimateALPR-SDK/binaries/jetson_tftrt/aarch64$ g++ test.cpp -O3 -I../../../c++ -L../aarch64/ -lultimate_alpr-sdk `pkg-config --cflags --libs opencv4` -o test
ns-16g@ns16g-desktop:~/ultimateALPR-SDK/binaries/jetson_tftrt/aarch64$ ./test
./test: error while loading shared libraries: libultimate_alpr-sdk.so: cannot open shared object file: No such file or directory
```

```
ns-16g@ns16g-desktop:~/ultimateALPR-SDK/binaries/jetson_tftrt/aarch64$ g++ test.cpp -O3 -I../../../c++ -L../aarch64/ -llibultimate_alpr-sdk `pkg-config --cflags --libs opencv4` -o test
/usr/bin/ld: cannot find -llibultimate_alpr-sdk
collect2: error: ld returned 1 exit status
```

```
ns-16g@ns16g-desktop:~/ultimateALPR-SDK/binaries/jetson_tftrt/aarch64$ g++ test.cpp -O3 -I../../../c++ -L../aarch64/ -llibultimate_alpr-sdk.so `pkg-config --cflags --libs opencv4` -o test
/usr/bin/ld: cannot find -llibultimate_alpr-sdk.so
collect2: error: ld returned 1 exit status
```

Directory :--
```
ns-16g@ns16g-desktop:~/ultimateALPR-SDK/binaries/jetson_tftrt/aarch64$ ls
benchmark                                  libtensorflow_cc.so.2         libtensorflow_framework.so.2.4.0  prepare.sh       runtimeKey    test.cpp
libtensorflow_2.4.0-rc1_jetson_gpu.tar.xz  libtensorflow_cc.so.2.4.0     libultimate_alpr-sdk.so           python_setup.sh  symlinks.bat  trt_optimizer
libtensorflow_cc.so                        libtensorflow_framework.so.2  libultimatePluginTensorRT.so      recognizer       test2.cpp     ultimateALPR-SDK-API-PUBLIC.h
```

**Comment by DoubangoTelecom** [comment]
Sorry but you don't seem to have experience in C++. You should consider using another language (Java, Python, C#...). Another problem is that you don't read the documentation and keeps opening issues.
You have a linking error and adding `-lultimate_alpr-sdk` **fixed** the issue. Now the issue is no longer linking but happens when you run 'test'. 

You said "There is no ultimate_alpr-sdk file in this directory." -> when you link to a library named `libSomeging.so`, the LDFLAGS must be `-lsomething`. Notice `lib` and `.so` are missing.

Last, if you take time reading the documentation you'd not keep opening tickets and asking questions. You have `error while loading shared libraries: libultimate_alpr-sdk.so: cannot open shared object file:` because you're not adding `LD_LIBRARY_PATH=...` as explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#testing-examples

**Comment by DoubangoTelecom** [comment]
You have already built test. Now to run it:
```
LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./test \
    --image ../../../assets/images/lic_us_1280x720.jpg \
    --assets ../../../assets \
    --charset latin \
    --parallel false \
    --rectify true
```
this command is from https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#testing-examples
Google `LD_LIBRARY_PATH` to understand why it's needed and how to avoid it.

**Comment by DoubangoTelecom** [comment]
Another note:  As explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md#known-issues-and-possible-fixes_slow-load-and-initialization use binaries in `jetson` instead of `jetson_tftrt` for dev. Anyways, on a 2GB nano device you'll not have a real boost when using `jetson_tftrt`. Check https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md#benchmark. On Jetson NX, `jetson_tftrt` is 2 times faster than `jetson` but on nano the gain is marginal.

**Comment by rsingh2083** [comment]
> You have already built test. Now to run it:
> 
> ```
> LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./test \
>     --image ../../../assets/images/lic_us_1280x720.jpg \
>     --assets ../../../assets \
>     --charset latin \
>     --parallel false \
>     --rectify true
> ```
> 
> this command is from https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#testing-examples
> Google `LD_LIBRARY_PATH` to understand why it's needed and how to avoid it.

Please look at the code Ive posted. Im trying to process a video.mp4 file, thats why Im compiling this new code

**Comment by rsingh2083** [comment]
> LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./test \
>     --image ../../../assets/images/lic_us_1280x720.jpg \
>     --assets ../../../assets \
>     --charset latin \
>     --parallel false \
>     --rectify true

TRIED BUT THIS ERROR :-
```
uracy.html#golden-number.
***[COMPV ERROR]: function: "read()" 
file: "/home/ultimate/compv/base/compv_fileutils.cxx" 
line: "268" 
message: [FileUtils] File at /root/ultimateALPR-SDK/assets/models.tensorrt/versions.txt is empty or doesn't exist
***[COMPV ERROR]: function: "readVersions()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
line: "265" 
message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
***[COMPV ERROR]: function: "optimizedPath()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
line: "212" 
message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
line: "257" 
message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
line: "131" 
message: [UltAlprSdkEngine] Failed to initialize the engine
test: test.cpp:48: int main(): Assertion `__ULTALPR_SDK_b_ret' failed.
Aborted (core dumped)

```

**Comment by DoubangoTelecom** [comment]
> > You have already built test. Now to run it:
> > ```
> > LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./test \
> >     --image ../../../assets/images/lic_us_1280x720.jpg \
> >     --assets ../../../assets \
> >     --charset latin \
> >     --parallel false \
> >     --rectify true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this command is from https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#testing-examples
> > Google `LD_LIBRARY_PATH` to understand why it's needed and how to avoid it.
> 
> Please look at the code Ive posted. Im trying to process a video.mp4 file, thats why Im compiling this new code. The code already has a video file specified, just help me to run it. I dont want to run on images

The fact that it's new code **doesn't matter**. There is documentation on how to compile the recognizer and you MUST use it as reference. All build issues you reported here were fixed using the existing documentation about how to build the samples.
Don't cut logs when reporting an error. Your logs are cut and we have no idea what's going on.

**Comment by DoubangoTelecom** [comment]
> > LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./test 
> > --image ../../../assets/images/lic_us_1280x720.jpg 
> > --assets ../../../assets 
> > --charset latin 
> > --parallel false 
> > --rectify true
> 
> TRIED BUT THIS ERROR :-
> 
> ```
> uracy.html#golden-number.
> ***[COMPV ERROR]: function: "read()" 
> file: "/home/ultimate/compv/base/compv_fileutils.cxx" 
> line: "268" 
> message: [FileUtils] File at /root/ultimateALPR-SDK/assets/models.tensorrt/versions.txt is empty or doesn't exist
> ***[COMPV ERROR]: function: "readVersions()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
> line: "265" 
> message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
> ***[COMPV ERROR]: function: "optimizedPath()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
> line: "212" 
> message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
> ***[COMPV ERROR]: function: "init()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
> line: "257" 
> message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
> ***[COMPV ERROR]: function: "init()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
> line: "131" 
> message: [UltAlprSdkEngine] Failed to initialize the engine
> test: test.cpp:48: int main(): Assertion `__ULTALPR_SDK_b_ret' failed.
> Aborted (core dumped)
> ```

The fact that it's new code **doesn't matter**. There is documentation on how to compile the recognizer and you MUST use it as reference. All build issues you reported here were fixed using the existing documentation about how to build the samples.
Don't cut logs when reporting an error. Your logs are cut and we have no idea what's going on.

**Comment by rsingh2083** [comment]
I got it running finally :--
In the c++ code i changed the line to correct path of assets folder 
`"\"assets_folder\": \"/home/ns-16g/ultimateALPR-SDK/assets\","`
Then I compiled and its running.
Thanks buddy

**Comment by rsingh2083** [comment]
Now one final request and Im done on ALPR.
Can you tell me what changes to do in my present c++ code to make it run on camera video instead of offline video ?

**Comment by DoubangoTelecom** [comment]
> > LD_LIBRARY_PATH=../../../binaries/jetson_tftrt/aarch64:$LD_LIBRARY_PATH ./test 
> > --image ../../../assets/images/lic_us_1280x720.jpg 
> > --assets ../../../assets 
> > --charset latin 
> > --parallel false 
> > --rectify true
> 
> TRIED BUT THIS ERROR :-
> 
> ```
> uracy.html#golden-number.
> ***[COMPV ERROR]: function: "read()" 
> file: "/home/ultimate/compv/base/compv_fileutils.cxx" 
> line: "268" 
> message: [FileUtils] File at /root/ultimateALPR-SDK/assets/models.tensorrt/versions.txt is empty or doesn't exist
> ***[COMPV ERROR]: function: "readVersions()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
> line: "265" 
> message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
> ***[COMPV ERROR]: function: "optimizedPath()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_trt.cxx" 
> line: "212" 
> message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
> ***[COMPV ERROR]: function: "init()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
> line: "257" 
> message: Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> 
> ***[COMPV ERROR]: function: "init()" 
> file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
> line: "131" 
> message: [UltAlprSdkEngine] Failed to initialize the engine
> test: test.cpp:48: int main(): Assertion `__ULTALPR_SDK_b_ret' failed.
> Aborted (core dumped)
> ```

Hum... checked again you command. WHY DID YOU REMOVE ` \`? Now you're 

> I got it running finally :--
> In the c++ code i changed the line to correct path of assets folder
> `"\"assets_folder\": \"/home/ns-16g/ultimateALPR-SDK/assets\","`
> Then I compiled and its running.
> Thanks buddy

BECAUSE YOU REMOVE `\` and everything after the first line is ignored. `--assets ...` is ignored because of this.

**Comment by rsingh2083** [comment]
Also will you send the licenses right away after I do payment ? Because I need it right now, have to prepare for a demo

**Comment by DoubangoTelecom** [comment]
> Now one final request and Im done on ALPR.
> Can you tell me what changes to do in my present c++ code to make it run on camera video instead of offline video ?

No, the only sample we have about video is for Android: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/android/videoparallel. For us this is out of scoop and we don't provide support for it. Up to you to write code reading images from camera or RTSP stream.

**Comment by DoubangoTelecom** [comment]
Also check https://groups.google.com/g/doubango-ai, there are entries about RTSP and video in general

**Comment by DoubangoTelecom** [comment]
> Also will you send the licenses right away after I do payment ? Because I need it right now, have to prepare for a demo

You may "need it right now" but you'll only get them when someone is available to add your company to the license manager. There is documentation to read on how the license manager work and activate. You seem to be in a rush and skip reading documentation. I feel like it would be a nightmare to provide support.
