### ISSUE TITLE
run the recognizer on linux

### ISSUE THREAD

**Issue by TonySchneider** [DoubangoTelecom/ultimateALPR-SDK#18]
Is there any option to run the recognizer on Linux?
I see the examples on Raspbian OS but I need it on ubuntu.
As far as I saw, there is a file called "libultimate_alpr-sdk.so", Is it possible to run this file on Ubuntu?
Thank you.

**Comment by DoubangoTelecom** [comment]
For now only Android and Raspberry Pi binaries are released. Next to come: iOS.

**Comment by DoubangoTelecom** [comment]
Version 2.7.0 makes Linux x86_64 binaries public:
- C++ samples: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B
