### ISSUE TITLE
Add support for Chinese license plates 

### ISSUE THREAD

**Issue by DoubangoTelecom** [DoubangoTelecom/ultimateALPR-SDK#188]

**Comment by davidfungf** [comment]
It can recognize the Chinese license plate. Works very well except the Chinese characters. Any support plan?
![test](https://user-images.githubusercontent.com/3412715/142755377-1d632e09-bfb1-4aad-8ed4-968b79ca0b82.jpg)
Suppose it is 粵ZG969港

**Comment by DoubangoTelecom** [comment]
> It can recognize the Chinese license plate. Works very well except the Chinese characters. Any support plan? ![test](https://user-images.githubusercontent.com/3412715/142755377-1d632e09-bfb1-4aad-8ed4-968b79ca0b82.jpg) Suppose it is 粵ZG969港

Check https://www.doubango.org/webapps/alpr-china/

**Comment by davidfungf** [comment]
Very nice!! Thanks.
