### ISSUE TITLE
Some queries  from client

### ISSUE THREAD

**Issue by AdityaZ12** [DoubangoTelecom/ultimateALPR-SDK#189]
Hello Sir,
Please reply to the queries you think are valid , rest we will try to research and figure out

1.] Is your algorithm capable of high speed ANPR at around 60KMPH ?
   If no then whats the minimum acceptable vehicle speed/relative speed

2.] What is the maximum distance your device can do ANPR from ?
   50 metres/100m /200m etc ?

3.] How will you handle ANPR in low light or at night time ?
    Here I need your valuable suggestions for cameras please.

**Comment by DoubangoTelecom** [comment]
Please use the developer group for question and the issue tracker to report issues.
