### ISSUE TITLE
The source code !!!

### ISSUE THREAD

**Issue by Baxulio** [DoubangoTelecom/ultimateALPR-SDK#2]
Please can you provide the source code of your ALPR solution. Thanks from the Republic of Uzbekistan :)

**Comment by DoubangoTelecom** [comment]
The Computer vision part is open source: https://github.com/DoubangoTelecom/CompV 
The Deep learning part is closed source for now: https://github.com/DoubangoTelecom/ultimateALPR 
To test the accuracy for your country: https://doubango.org/webapps/alpr/

**Comment by DoubangoTelecom** [comment]
BTW, I've added support for "Republic of Uzbekistan" in the training data. You can test it at https://doubango.org/webapps/alpr/
