### ISSUE TITLE
Vesion v4.0

### ISSUE THREAD

**Issue by DoubangoTelecom** [DoubangoTelecom/ultimateALPR-SDK#204]
We're working on version v4.0 and already started to deploy it at https://www.doubango.org/webapps/alpr/. The result from the SDK may not be the same as the online demo.

**Comment by renatovaler** [comment]
Is there an expected release date?

**Comment by ahrakos** [comment]
Any release date?

**Comment by msavara** [comment]
> We're working on version v4.0 and already started to deploy it at https://www.doubango.org/webapps/alpr/. The result from the SDK may not be the same as the online demo.

May I ask when this version will be released? Thank you for your answer.

**Comment by DoubangoTelecom** [comment]
https://groups.google.com/d/msgid/doubango-ai/9d736433-1707-4487-8e55-9df26cd8cf68n%40googlegroups.com
