### ISSUE TITLE
Error with GPU enabled

### ISSUE THREAD

**Issue by gio2375** [DoubangoTelecom/ultimateALPR-SDK#206]
Hello, I'm testing the sample application Recognizer (Java version). All works well if I use CPU but, if I try GPU I get the errors you can see in attacched file. My Video card is an Nvidia Gforce GTX 950M.

Thanks
Giovanni

[GPU_error.txt](https://github.com/DoubangoTelecom/ultimateALPR-SDK/files/7473909/GPU_error.txt)

**Comment by DoubangoTelecom** [comment]
Hello,
Do not use `"openvino_device": "GPU"` on NVIDIA GPUs. Use OpenVINO GPU computing on Intel GPUs only (e.g. NCS2). You have an Nvidia Geforce GTX 950M with support for CUDA. Tensorflow supports CUDA and you check https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B#gpu-acceleration. Please note that you have to correctly install CUDA libraries and drivers first.

**Comment by DoubangoTelecom** [comment]
Please also note that you have a very low end GPU (https://www.techpowerup.com/gpu-specs/geforce-gtx-950m.c2642). You'll not see significant boost
