### ISSUE TITLE
Cant run android sample due to gradle issue

### ISSUE THREAD

**Issue by parkcheck** [DoubangoTelecom/ultimateALPR-SDK#207]
I am using most recent code from git:

`
FAILURE: Build failed with an exception.

* What went wrong:
Task 'wrapper' not found in project ':videosequential'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

The build scan was not published due to a configuration problem.

The Gradle Terms of Service have not been agreed to.

For more information, please see https://gradle.com/help/plugin-terms-of-service.

Alternatively, if you are using Gradle Enterprise, specify the server location.
For more information, please see https://gradle.com/help/plugin-enterprise-config.`

**Comment by DoubangoTelecom** [comment]
Add information about your android studio version, operating system and how you're trying to import the project.
