### ISSUE TITLE
Running On Mac Os Big Sur

### ISSUE THREAD

**Issue by rickysut** [DoubangoTelecom/ultimateALPR-SDK#208]
Hi, 
I try to build your SDK on mac , which no os folder for mac (thereis but only empty folder actually). So I go to Linux folder. But I got 3 warning and the extension _ultimateAlprSdk.so not build yet.
Is there a way to compile sdk on mac? can you give me the step?

[screen capture]
python ../../../python/setup.py build_ext --inplace -v 
Your platform: darwin
running build_ext
building '_ultimateAlprSdk' extension
creating build
creating build/temp.macosx-11-x86_64-3.9
creating build/temp.macosx-11-x86_64-3.9/Users
creating build/temp.macosx-11-x86_64-3.9/Users/rickysut
creating build/temp.macosx-11-x86_64-3.9/Users/rickysut/Development
creating build/temp.macosx-11-x86_64-3.9/Users/rickysut/Development/ultimateALPR-SDK-master
creating build/temp.macosx-11-x86_64-3.9/Users/rickysut/Development/ultimateALPR-SDK-master/python
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I../../../c++ -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /Users/rickysut/Development/ultimateALPR-SDK-master/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.cxx -o build/temp.macosx-11-x86_64-3.9/Users/rickysut/Development/ultimateALPR-SDK-master/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.o
/Users/rickysut/Development/ultimateALPR-SDK-master/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.cxx:2391:23: warning: 
      explicitly assigning value of variable of type 'int' to itself
      [-Wself-assign]
                  res = SWIG_AddCast(res);
                  ~~~ ^              ~~~
/Users/rickysut/Development/ultimateALPR-SDK-master/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.cxx:2394:23: warning: 
      explicitly assigning value of variable of type 'int' to itself
      [-Wself-assign]
                  res = SWIG_AddCast(res);                  
                  ~~~ ^              ~~~
In file included from /Users/rickysut/Development/ultimateALPR-SDK-master/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.cxx:3574:
../../../c++/ultimateALPR-SDK-API-PUBLIC.h:239:24: warning: deleted function
      definitions are a C++11 extension [-Wc++11-extensions]
                UltAlprSdkEngine() = delete;
                                     ^
3 warnings generated.
clang -bundle -undefined dynamic_lookup build/temp.macosx-11-x86_64-3.9/Users/rickysut/Development/ultimateALPR-SDK-master/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.o -L. -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -lultimate_alpr-sdk -o /Users/rickysut/Development/ultimateALPR-SDK-master/binaries/linux/x86_64/_ultimateAlprSdk.so
ld: warning: ignoring file ./libultimate_alpr-sdk.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )

**Comment by DoubangoTelecom** [comment]
MacOS not supported

**Comment by DoubangoTelecom** [comment]
https://www.doubango.org/SDKs/anpr/docs/Architecture_overview.html#supported-operating-systems
