### ISSUE TITLE
-bash: ./recognizer: No such file or directory

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#215]
Iwas able to compile the recognizer on Khadas vim3 but while running example recognizer binary, Im getting this error :- 
`-bash: ./recognizer: No such file or directory`

How to reproduce :-

```
khadas@Khadas:~/ultimateALPR-SDK/binaries/raspbian/armv7l$ LD_LIBRARY_PATH=../../../binaries/raspbian/armv7l:$LD_LIBRARY_PATH ./recognizer \
>     --image ../../../assets/images/lic_us_1280x720.jpg \
>     --assets ../../../assets \
>     --charset latin \
>     --parallel false \
>     --rectify true
-bash: ./recognizer: No such file or directory
```

But recognizer is there in the directory :-
```
khadas@Khadas:~/ultimateALPR-SDK/binaries/raspbian/armv7l$ ls
README.md  benchmark  libultimate_alpr-sdk.so  python_setup.sh  recognizer  runtimeKey
```

**Comment by DoubangoTelecom** [comment]
Off course you cannot run an ARM 32-bit code (Raspbian) on a 64-bit board. We cannot provide additional help because you're not telling us what OS and arch you have installed on your board.
