### ISSUE TITLE
How to directly decode a binary into a structure which ultimateALPR-SDK can recognize?

### ISSUE THREAD

**Issue by mochechan** [DoubangoTelecom/ultimateALPR-SDK#217]
With the [sample](https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c%2B%2B/recognizer/recognizer.cxx#L230), a file can be loaded and decoded into a structure which ultimateALPR-SDK can recognize. 

For performance consideration, suppose I have a jpg image binary saved as std::string in RAM, and I do not want to save as a file  loaded for ultimateALPR-SDK. How to directly decode the std::string as the input structure for ultimateALPR-SDK?

**Comment by DoubangoTelecom** [comment]
If you check https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#readme  you'll read **The application accepts path to a JPEG/PNG/BMP file as input. This is not the recommended way to use the API. ** 

Check the API function and you'll see that the processing function accept an image from a buffer (RAM). For std::string you'll pass string.c_str() memory address to the process function. https://www.doubango.org/SDKs/anpr/docs/cpp-api.html#_CPPv4N15ultimateAlprSdk16UltAlprSdkEngine7processEK22ULTALPR_SDK_IMAGE_TYPEPKvK6size_tK6size_tK6size_tKi

**Comment by DoubangoTelecom** [comment]
In the future please use the dev-group (https://groups.google.com/g/doubango-ai) for technical questions and this issue tracker to report bugs.
