### ISSUE TITLE
Error in adding symbol : file format not supported

### ISSUE THREAD

**Issue by AjinkyaDeshpande39** [DoubangoTelecom/ultimateALPR-SDK#219]
D:\ultimateALPR-SDK\binaries\windows\x86_64>python36 ../../../python/setup.py build_ext --inplace -v
Your platform: win32
running build_ext
building '_ultimateAlprSdk' extension
C:\MinGW\bin\gcc.exe -mdll -O -Wall -I../../../c++ -IC:\Users\Asus\AppData\Local\Programs\Python\Python36\include -IC:\Users\Asus\AppData\Local\Programs\Python\Python36\include -c D:\ultimateALPR-SDK\python\ultimateALPR-SDK-API-PUBLIC-SWIG_python.cxx -o d:\ultimatealpr-sdk\python\ultimatealpr-sdk-api-public-swig_python.o
writing d:\ultimatealpr-sdk\python\_ultimateAlprSdk.def
C:\MinGW\bin\gcc.exe -shared -s d:\ultimatealpr-sdk\python\ultimatealpr-sdk-api-public-swig_python.o d:\ultimatealpr-sdk\python\_ultimateAlprSdk.def -L. -LC:\Users\Asus\AppData\Local\Programs\Python\Python36\libs -LC:\Users\Asus\AppData\Local\Programs\Python\Python36\PCbuild\amd64 -lultimateALPR-SDK -lpython36 -lmscvr160 -o D:\ultimateALPR-SDK\binaries\windows\x86_64\_ultimateAlprSdk.pyd
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Asus\AppData\Local\Programs\Python\Python36\libs/libpython36.a: error adding symbols: file format not recognized
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1

Please help me geet rid of this error

Visual studio version - 16.11.7
[MSC v.1900 64 bit (AMD64)] on win32
Python3.6.0 version

In cygwincompiler.py i have put 
        elif msc_ver == '1900':
            return ['mscvr160']
and added distutils.cfg with -
[build]
compiler=mingw32
to remove vcvarsall.bat not found error

**Comment by DoubangoTelecom** [comment]
On Windows building the Python extension was tested using Visual Studio only. We haven't tested MinGW+GCC. Your logs shows MinGW+GCC is being used. https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/python/README.md#c-compiler
