### ISSUE TITLE
Got the LPR result question

### ISSUE THREAD

**Issue by er778899789** [DoubangoTelecom/ultimateALPR-SDK#221]
Hi, I build this application in Python. 
Below image is I test with my photo.
![R1](https://user-images.githubusercontent.com/32409355/144528340-c1145005-be2c-4b1b-af13-261cdc701e84.PNG)
![R2](https://user-images.githubusercontent.com/32409355/144528355-25fd5318-7ad5-427b-9644-000bbf82fc2d.PNG)
![R3](https://user-images.githubusercontent.com/32409355/144528362-a2c4760f-443a-4b02-9373-8f9eb08d01da.PNG)

Why my text OCR always get the last char with '*' in each image.
I build this in trial version. How can I build normal version in my device? Need to buy licence?

**Comment by DoubangoTelecom** [comment]
The last char is obfuscated on purpose because no license is provided. You're using a trial version.

**Comment by er778899789** [comment]
@DoubangoTelecom  Sorry, Can I ask what LP OCR model you use in newest version?
Openalpr seems to use tesseract to get the OCR result.

**Comment by DoubangoTelecom** [comment]
> @DoubangoTelecom Sorry, Can I ask what LP OCR model you use in newest version? Openalpr seems to use tesseract to get the OCR result.

Unfortunately that information is confidential.

**Comment by er778899789** [comment]
@DoubangoTelecom Sorry to bother you.
How can I get commercial license to unlock the symbol ‘*’

**Comment by DoubangoTelecom** [comment]
> @DoubangoTelecom Sorry to bother you. How can I get commercial license to unlock the symbol ‘*’

https://www.doubango.org/pricing.html
