### ISSUE TITLE
how to porting this sdk to other embedded device?

### ISSUE THREAD

**Issue by pppaulpeter** [DoubangoTelecom/ultimateALPR-SDK#232]
Hi,

thanks for sharing this library, may i know how to porting this sdk to other embedded device? any clue? thanks!

**Comment by DoubangoTelecom** [comment]
This work on all ARM and x86 devices

**Comment by pppaulpeter** [comment]
> This work on all ARM and x86 devices

Hi, 
thanks for quick response. but do  i need recompile the recognizer applciation and the dynamic library?

**Comment by DoubangoTelecom** [comment]
32-bit ARM is only supported on Android. We also don't support 32-bit x86. My previous comment lack precision: "We support all 64-bit ARM and x86 devices"

**Comment by cebecifaruk** [comment]
> 32-bit ARM is only supported on Android. We also don't support 32-bit x86. My previous comment lack precision: "We support all 64-bit ARM and x86 devices"

Why there is no support for 32-bit ARM architecture? In my company, we design embedded hardware for ultimate-alpr.  We are designing Allwinner SoC based boards. However, It is not convenient to use BCM SOC based boards for us.

**Comment by DoubangoTelecom** [comment]
> > 32-bit ARM is only supported on Android. We also don't support 32-bit x86. My previous comment lack precision: "We support all 64-bit ARM and x86 devices"
> 
> Why there is no support for 32-bit ARM architecture? In my company, we design embedded hardware for ultimate-alpr. We are designing Allwinner SoC based boards. However, It is not convenient to use BCM SOC based boards for us.

Lack of opportunities. Almost all requests we have from our customers are for 64-bit ARM. Maintaining an architecture requires time and resource. We cannot spend time on a platform to sell few licenses per year. Also the code is heavily optimized using assembler for 64-bit archs but not 32-bit.

**Comment by DoubangoTelecom** [comment]
Duplicate of #238
