### ISSUE TITLE
Confidences in JSON 8 values => API Python instead of 2 values API C++

### ISSUE THREAD

**Issue by ccs2epro** [DoubangoTelecom/ultimateALPR-SDK#240]
Hey, 
I am migrating from the C++ API to the python API, and I noticed that the confidences field in the JSON has 8 values against 2 for C++ (you told me that this corresponds to [OCR recognition score, plate detection score]).
What do these 8 values correspond to? Is it a mistake?

**Comment by DoubangoTelecom** [comment]
Hi,
There is no difference between the languages. If there are 2 values it means there is no OCR result. The length for the confidence array is variable, check https://www.doubango.org/SDKs/anpr/docs/Frequently_Asked_Questions_(FAQ).html#could-you-explain-what-each-field-in-the-json-result-mean

You may not have OCR result when Parallel mode is enabled, read documentation about it. Probably have Parallel mode enabled in c++ and disabled in python which produce different results.

Please attach the logs.
