### ISSUE TITLE
Some of the characters are being read inaccurately

### ISSUE THREAD

**Issue by shalayush** [DoubangoTelecom/ultimateALPR-SDK#253]
Dear Sir,

PFA attached picture. As you can see "Z" is being read as "2", how can we fix this issue. What config parameters we need to use in order to achieve maximum accuracy ?

https://ibb.co/gmSRmn6

**Comment by DoubangoTelecom** [comment]
We don't have this kind of plate in the training set. The model has to be retrained with a lot of samples o this type
