### ISSUE TITLE
Error with Testing SDK before purchasing -- Help 

### ISSUE THREAD

**Issue by pans007** [DoubangoTelecom/ultimateALPR-SDK#257]
Hi There, 
Please can you help with our error (attached Screenshot) Error is Illegal Instuction 

<img width="1241" alt="Screenshot 2022-06-30 at 14 25 19" src="https://user-images.githubusercontent.com/108469270/176676740-c642a49c-01b5-4c95-9ce5-b726d3bbbc4c.png">

**Comment by DoubangoTelecom** [comment]
https://groups.google.com/g/doubango-ai/c/sLSBDtVqYaI
