### ISSUE TITLE
Python UltAlprSdkParallelDeliveryCallback

### ISSUE THREAD

**Issue by edsalazarx** [DoubangoTelecom/ultimateALPR-SDK#258]
Hi 

can give me a sample how set parrallel on python version

**Comment by DoubangoTelecom** [comment]
Hi,
Python doesn't support true multithreading. This feature isn't supported for Python 
https://www.doubango.org/SDKs/anpr/docs/Frequently_Asked_Questions_(FAQ).html#why-the-recognizer-application-is-slow
