### ISSUE TITLE
How to detect small plates reliably

### ISSUE THREAD

**Issue by srodriguezvisability** [DoubangoTelecom/ultimateALPR-SDK#271]
Im testing the library but it does not seem to work properly. In the following example I have a full image where a car is cleary visible (top rigth) https://drive.google.com/file/d/1Twv3RD_L_pfO0NDPQX2KKvEwUEVOf-1R/view?usp=share_link

However, if I crop the area and process it, it works https://drive.google.com/file/d/1mDMiMbflqpCWaWCO4StbQADTpB1eB-Ny/view?usp=share_link

I have tested the images both in your web https://www.doubango.org/webapps/alpr/, and with your code using many different values for the different parameters.
  
ROI (https://www.doubango.org/SDKs/anpr/docs/Improving_the_accuracy.html#far-away-or-very-small-plates)

is not an option since the car can be anywhere in the image. I was using the pyramidal search and is not working. I am using the following params (and combinations of it). Any other possible way to solve the issue? Thanks

*[COMPV INFO]: [UltAlprSdkEngine] jsonConfig: {"debug_level": "info","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","num_threads": 2,"gpgpu_enabled": true,"openvino_enabled": true,"openvino_device": "CPU","detect_roi": [0, 0, 0, 0],"detect_minscore": 0.1,"pyramidal_search_enabled": true,"pyramidal_search_sensitivity": 1.0,"pyramidal_search_minscore": 0.15,"pyramidal_search_quantization_enabled": true,"pyramidal_search_min_image_size_inpixels": 100,"klass_lpci_enabled": false,"klass_vcr_enabled": false,"klass_vmm_enabled": false,"recogn_minscore": 0.3,"recogn_score_type": "min","recogn_tf_num_threads": 1,"car_noplate_detect_enabled":false,"recogn_rectify_enabled": true,"recogn_quantization_enabled": true,"assets_folder": "../../trunk/3rdparty/ultimateALPR/assets/"}
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx' in function 'init' starting at line #77: Not optimized -> Code not built for mobile devices but for clouds. Are you sure this is what you want?

**Comment by DoubangoTelecom** [comment]
Please don't open multiple threads. Duplicate #270
