### ISSUE TITLE
Error with OpenVino

### ISSUE THREAD

**Issue by ashjaymohsin** [DoubangoTelecom/ultimateALPR-SDK#273]
These are my error logs. I can't seem to get OpenVINO running Keep in mind that i've already installed visual studio C++ redistributable and checked the dependencies of ultimatePluginOpenVINO.dll

C:\Users\HP\Downloads\ultimateALPR-SDK-master\binaries\windows\x86_64>benchmark.exe     --positive ../../../assets/images/lic_us_1280x720.jpg     --negative ../../../assets/images/london_traffic.jpg     --assets ../../../assets     --ienv_enabled false     --openvino_enabled true     --openvino_device GPU     --klass_lpci_enabled false     --klass_vcr_enabled false     --klass_vmmr_enabled false     --klass_vbsr_enabled false     --charset latin     --loops 100     --rate 0.2     --parallel true
*[ULTALPR_SDK INFO]: Starting benchmark...
*[COMPV INFO]: [UltAlprSdkEngine]Call: ultimateAlprSdk::UltAlprSdkEngine::init
*[COMPV INFO]: [UltAlprSdkEngine]jsonConfig: {"debug_level": "info","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","gpgpu_enabled": true,"max_latency": -1,"klass_vcr_gamma": 1.5,"detect_roi": [0, 0, 0, 0],"detect_minscore": 0.1,"pyramidal_search_enabled": false,"pyramidal_search_sensitivity": 0.28,"pyramidal_search_minscore": 0.8,"pyramidal_search_min_image_size_inpixels": 800,"recogn_minscore": 0.3,"recogn_score_type": "min","assets_folder": "../../../assets","charset": "latin","num_threads": -1,"recogn_rectify_enabled": false,"ienv_enabled": false,"openvino_enabled": true,"openvino_device": "GPU","npu_enabled": true,"asm_enabled": true,"intrin_enabled": true,"klass_lpci_enabled": false,"klass_vcr_enabled": false,"klass_vmmr_enabled": false,"klass_vbsr_enabled": false}
*[COMPV INFO]: [UltAlprSdkEngine]**** Copyright (C) 2011-2023 Doubango Telecom <https://www.doubango.org> ****
ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK> version 3.11.0

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #8
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: [CompVBase] Windows dwMajorVersion=6, dwMinorVersion=2
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] H: 'GenuineIntel', S: '', M: '', MN: ''
*[COMPV INFO]: [CompVBase] CPU features: (intel);[x86];[x64];mmx;sse;sse2;sse3;ssse3;sse41;sse42;avx;avx2;fma3;erms;bmi1;bmi2;popcnt;cmov;aes;rdrand;
*[COMPV INFO]: [CompVBase] CPU cores: online=#4, conf=#4
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #64B, size :#32KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #8109GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: X86_64
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] OS name: Windows
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #64
*[COMPV INFO]: [CompVBase] Best alignment: #64
*[COMPV INFO]: [CompVBase] Heap limit: #415187KB (#405MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: /!\ Code in file 'compv_mem.cxx' in function 'compv::CompVMemZero_C' starting at line #508: Not optimized -> No SIMD implementation found
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #4 threads/#4 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=0,set=useless, threadId:0000000000002A7C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=3,set=useless, threadId:00000000000005B0, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=2,set=useless, threadId:0000000000003020, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=1,set=useless, threadId:0000000000001294, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Camera plugin path: C:\Users\HP\Downloads\ultimateALPR-SDK-master\binaries\windows\x86_64\CompVPluginMFoundation.dll
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file 'source\ultimate_base_engine.cxx' in function 'ultimateBase::UltBaseEngine::init' starting at line #75: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [OpenCL.dll]
*[COMPV INFO]: [CompVSharedLib] Loading sharded library from OpenCL.dll
*[COMPV INFO]: [UltBaseOpenCL] Loaded [OpenCL.dll], looksLikeValid: yes...
*[COMPV INFO]: [UltBaseOpenCLUtils] Selected platform vendor: Intel(R) Corporation
*[COMPV INFO]: [UltBaseOpenCLUtils] deviceCount=1
*[COMPV INFO]: [UltBaseOpenCLUtils] Device -> name: Intel(R) HD Graphics 620, id: 0000020F088702D0
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT=1
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE=1
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_COMPUTE_UNITS=23
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS=3
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_SIZES=256, 256, 256,
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_GROUP_SIZE=256
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_CLOCK_FREQUENCY=1000 MHz
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE=64 B
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_SIZE=3401211904 B (3243 MB)
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_LOCAL_MEM_SIZE=65536 B (64 KB)
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_MEM_ALLOC_SIZE=1621 MB
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_PLATFORM_VERSION=OpenCL 2.1
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_VERSION=OpenCL 2.1 NEO
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DRIVER_VERSION=25.20.100.6518
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_OPENCL_C_VERSION=OpenCL C 2.0
***[COMPV ERROR]: function: "ultimateBase::UltBaseOpenCLUtils::init()"
file: "source\opencl\ultimate_base_opencl_utils.cxx"
line: "96"
message: [UltBaseOpenCLUtils] OpenCL operation failed (-30 -> CL_INVALID_VALUE) ->
***[COMPV ERROR]: function: "ultimateBase::UltBaseOpenCLUtils::init()"
file: "source\opencl\ultimate_base_opencl_utils.cxx"
line: "106"
message: Operation Failed (COMPV_ERROR_CODE_E_UNKNOWN) ->
*[COMPV INFO]: [UltBaseOpenCL] Failed to hook functions using [OpenCL.dll] library
*[COMPV INFO]: [UltOcrEngine] Tensorflow version: 1.15.0
*[COMPV INFO]: [UltAlprPlugin] Loading plugin: C:\Users\HP\Downloads\ultimateALPR-SDK-master\binaries\windows\x86_64\ultimatePluginOpenVino.dll ...
*[COMPV INFO]: [CompVSharedLib] Loading sharded library from C:\Users\HP\Downloads\ultimateALPR-SDK-master\binaries\windows\x86_64\ultimatePluginOpenVino.dll
***[COMPV ERROR]: function: "compv::CompVSharedLib::open()"
file: "compv_sharedlib.cxx"
line: "69"
message: [CompVSharedLib] Failed to load library with path=C:\Users\HP\Downloads\ultimateALPR-SDK-master\binaries\windows\x86_64\ultimatePluginOpenVino.dll, Error: 0x0000007f
***[COMPV ERROR]: function: "compv::CompVSharedLib::open()"
file: "compv_sharedlib.cxx"
line: "73"
message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) ->
***[COMPV ERROR]: function: "compv::CompVSharedLib::newObj()"
file: "compv_sharedlib.cxx"
line: "119"
message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) ->
***[COMPV ERROR]: function: "ultimateAlpr::UltAlprPlugin::init()"
file: "source\ultimate_alpr_plugin.cxx"
line: "96"
message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) ->
*[COMPV INFO]: [UltAlprSdkEnginePrivate]**** Copyright (C) 2011-2023 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK>
without the rights to include the SDK in any form of commercial product.
*[COMPV INFO]: [UltAlprSdkEnginePrivate]IC took 71 millis
*[COMPV INFO]: [CompVCpu] Enabling asm code
*[COMPV INFO]: [CompVCpu] Enabling intrinsic code
*[COMPV INFO]: [UltAlprSdkEnginePrivate]recogn_tf_num_threads: 4, acceleration backend: OpenVino
*[COMPV INFO]: [CompVThreadDispatcher] Not optimized -> Your system have #4 cores but you're only using #3. Sad!!
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #3 threads/#4 cores
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=0,set=useless, threadId:000000000000245C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=1,set=useless, threadId:0000000000002444, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=2,set=useless, threadId:00000000000037BC, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] gpu_memory_alloc_max_percent = 0.100000
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] Alloc session with gpu_memory_alloc_max_percent = 10%
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] gpu_memory_alloc_max_percent = 0.100000
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] Alloc session with gpu_memory_alloc_max_percent = 10%
*[COMPV INFO]: [UltAlprSdkEnginePrivate]*** Entering parallel process for job #1 ***
*[COMPV INFO]: [UltAlprSdkEnginePrivate]*** Entering parallel process for job #0 ***
*[COMPV INFO]: [UltAlprSdkEnginePrivate]*** Entering parallel delivery ***
*[COMPV INFO]: [UltAlprSdkEngine]Call: ultimateAlprSdk::UltAlprSdkEngine::warmUp
*[COMPV INFO]: /!\ Code in file 'source\ultimate_alpr_detector.cxx' in function 'ultimateAlpr::UltAlprDetector::process' starting at line #29: Not optimized -> Batching will not be activated for this function
*[COMPV INFO]: /!\ Code in file 'source\ultimate_ocr_tensorflow_session_detect.cxx' in function 'ultimateOcr::UltOcrTensorflowSessionDetector::processInternal' starting at line #116: Not optimized -> Batching not supported for this function
*[COMPV INFO]: /!\ Code in file 'compv_mem.cxx' in function 'compv::CompVMemCopy_C' starting at line #985: Not optimized -> No SIMD implementation found. On ARM consider http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka13544.html
*[COMPV INFO]: /!\ Code in file 'intrin\x86\compv_mem_intrin_ssse3.cxx' in function 'compv::CompVMemUnpack3_SrcPtrNotAligned_Intrin_SSSE3' starting at line #69: Not built with SSSE3 support
*[COMPV INFO]: /!\ Code in file 'source\ultimate_text_fuser.cxx' in function 'ultimateText::UltTextFuser::process' starting at line #189: Is for testing and must not be called -> Fragments should be trimmed
*[COMPV INFO]: /!\ Code in file 'math\compv_math_matrix.cxx' in function 'compv::CompVMatrix::mulAtA' starting at line #881: Contains a TODO: -> Deprecated: use CompVMath::mulAB
*[COMPV INFO]: /!\ Code in file 'math\compv_math_matrix.cxx' in function 'compv::CompVMatrixGeneric<double>::transpose' starting at line #619: Not optimized -> No MT implementation could be found
*[COMPV INFO]: /!\ Code in file 'source\ultimate_text_slant.cxx' in function 'ultimateText::UltTextSlant::applyTransformation' starting at line #90: Not optimized -> Bundle homogenous transformation + transpose + mulABt + homogeneousToCartesian2D
*[COMPV INFO]: /!\ Code in file 'math\compv_math_matrix.cxx' in function 'compv::CompVMatrixGeneric<float>::transpose' starting at line #619: Not optimized -> No MT implementation could be found
*[COMPV INFO]: /!\ Code in file 'math\compv_math_transform.cxx' in function 'compv::CompVMathTransformGeneric<float>::homogeneousToCartesian2D' starting at line #98: Not optimized -> No SIMD or GPU implementation found
*[COMPV INFO]: /!\ Code in file 'math\compv_math_matrix.cxx' in function 'compv::CompVMatrixGeneric<float>::invA3x3' starting at line #515: Not optimized -> No SIMD or GPU implementation found.
*[COMPV INFO]: /!\ Code in file 'math\compv_math_matrix.cxx' in function 'compv::CompVMatrixGeneric<float>::invA3x3' starting at line #515: Not optimized -> No SIMD or GPU implementation found.
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 1): {"frame_id":3,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 2): {"frame_id":9,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92831,99.98941,90.19174,90.00758,90.07481,89.40962,90.07738,90.2903,87.92831],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 3): {"frame_id":21,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 4): {"frame_id":25,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92825,99.98941,90.19174,90.00771,90.07481,89.409,90.07771,90.29056,87.92825],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 5): {"frame_id":29,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 6): {"frame_id":31,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 7): {"frame_id":40,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 8): {"frame_id":43,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92831,99.98941,90.19161,90.0079,90.07494,89.40874,90.07753,90.29046,87.92831],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 9): {"frame_id":46,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19161,90.00755,90.07497,89.40894,90.07752,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 10): {"frame_id":49,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 11): {"frame_id":52,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92818,99.98941,90.19161,90.00799,90.07489,89.40853,90.07756,90.29049,87.92818],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 12): {"frame_id":53,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92819,99.98941,90.19158,90.00744,90.07494,89.40871,90.07755,90.29047,87.92819],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 13): {"frame_id":57,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.9283,99.98941,90.19174,90.00771,90.07481,89.40903,90.07774,90.2906,87.9283],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 14): {"frame_id":70,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 15): {"frame_id":74,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 16): {"frame_id":75,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92827,99.98941,90.1924,90.0099,90.07404,89.41037,90.07722,90.29076,87.92827],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 17): {"frame_id":82,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92907,99.98941,90.19176,90.00594,90.07455,89.41009,90.07806,90.29022,87.92907],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 18): {"frame_id":86,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92857,99.98941,90.19161,90.00649,90.07471,89.40923,90.07745,90.29068,87.92857],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 19): {"frame_id":92,"job_idx":1,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92813,99.98941,90.19174,90.00771,90.07478,89.40895,90.07755,90.29037,87.92813],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: MyUltAlprSdkParallelDeliveryCallback::onNewResult(0, OK, 20): {"frame_id":95,"job_idx":0,"latency":0,"plates":[{"car":{"confidence":100.0,"warpedBox":[82.07767,156.5956,1088.546,156.5956,1088.546,615.5728,82.07767,615.5728]},"confidences":[87.92815,99.98941,90.19183,90.00938,90.07561,89.40889,90.07758,90.29068,87.92815],"text":"3PEDLM*","warpedBox":[822.595,339.7195,915.2424,339.7195,915.2424,399.8867,822.595,399.8867]}]}
*[ULTALPR_SDK INFO]: Elapsed time (ALPR) = [[[ 7376.946600 millis ]]]
*[ULTALPR_SDK INFO]: result: {"duration":64,"frame_id":99,"latency":0}
*[ULTALPR_SDK INFO]: *** elapsedTimeInMillis: 7376.946600, estimatedFps: 13.555744 ***
*[ULTALPR_SDK INFO]: Press any key to terminate !!

**Comment by DoubangoTelecom** [comment]
Share dependency walker report. 
https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Dependencies.md

**Comment by ashjaymohsin** [comment]
[ultimatePluginOpenVINO.zip](https://github.com/DoubangoTelecom/ultimateALPR-SDK/files/11353801/ultimatePluginOpenVINO.zip)

**Comment by ashjaymohsin** [comment]
I have attached the dependency report, its in the zip file attached in the previous message

**Comment by DoubangoTelecom** [comment]
[ngraph.dll](https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/binaries/windows/x86_64/ngraph.dll) is missing on the binaries folder on your machine. Make sure you checked out everything and didn't delete any file.
