### ISSUE TITLE
Recogniser sample video stream

### ISSUE THREAD

**Issue by tomcass240** [DoubangoTelecom/ultimateALPR-SDK#277]
On the readme it has a video of the recogniser sample being used on a video stream but the readme for the application seems to only support jpg/bmp/png. Are you supposed to convert your video to a series of images for this software to work properly?

**Comment by DoubangoTelecom** [comment]
Sample code showing how to process video stream is available for Android only: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/android. It's straightforward to write your own code to process a video. Example, pseudo-code: https://www.doubango.org/SDKs/anpr/docs/Getting_started.html#opencv
