### ISSUE TITLE
runtimeKey binary no works on recent Khadas builds firmware

### ISSUE THREAD

**Issue by edsalazarx** [DoubangoTelecom/ultimateALPR-SDK#279]
**Khadas Fenix 1.0.11 :** 
*[COMPV INFO]: [UltAlprSdkEnginePrivate] recogn_tf_num_threads: 6, acceleration backend: AmlogicNPU
*[PLUGIN_AMLNPU INFO]: /!\ Code in file '/home/ultimateAmlogicNPU/pluginAmlogicNPU/source/plugin_amlnpu_interface.cxx' in function 'pluginAmlogicNPU_Engine_new' starting at line #113: Version: 1.0.0
****[PLUGIN_AMLNPU FATAL]: function: "pluginAmlDetect()" 
file: "/home/ultimateAmlogicNPU/pluginAmlogicNPU/source/plugin_amlnpu_detect.cxx" 
line: "59" 
message: [pluginAmlDetect] Graph verify failed: -1 -> A generic error code, used when no other describes the error.
****[PLUGIN_AMLNPU FATAL]: function: "pluginAmlDetect()" 
file: "/home/ultimateAmlogicNPU/pluginAmlogicNPU/source/plugin_amlnpu_detect.cxx" 
line: "60" 
message: Assertion failed!
Aborted

**Khadas Fenix 1.0.10 :** 
[PLUGIN_AMLNPU INFO]: /!\ Code in file '/home/ultimateAmlogicNPU/pluginAmlogicNPU/source/plugin_amlnpu_interface.cxx' in function 'pluginAmlogicNPU_Engine_new' starting at line #113: Version: 1.0.0
*[PLUGIN_AMLNPU INFO]: [pluginAmlDetect] Amlogic NPU-accelerated detector(detect_main) created
*[COMPV INFO]: [UltAlprDetector] We have managed to create /home/khadas/ultimateALPR-SDK/assets/models.amlogic_npu/PID0x88/ultimateALPR-SDK_detect_main.mobile.model.amlogic.doubango detector/classifier for AmlogicNPU. Ignoring Tensorflow detector/classifier.
*[PLUGIN_AMLNPU INFO]: [pluginAmlDetect] Amlogic NPU-accelerated detector(detect_pysearch) created
*[COMPV INFO]: [UltAlprDetector] We have managed to create /home/khadas/ultimateALPR-SDK/assets/models.amlogic_npu/PID0x88/ultimateALPR-SDK_detect_pysearch.mobile.model.amlogic.doubango detector/classifier for AmlogicNPU. Ignoring Tensorflow detector/classifier.
*[COMPV INFO]: [UltAlprSdkEngine]Call: requestRuntimeLicenseKey
*[COMPV INFO]: [UltBaseEngine]UltBaseEngineReadSystemFile: fgets[18446744073709551615] returned valid string
*[ULTALPR_SDK INFO]: 

{"runtimeKey":"*********************************************************************************"}

*[ULTALPR_SDK INFO]: Press any key to terminate !!

### 
Both tested on fresh instalations

**Comment by DoubangoTelecom** [comment]
NPU acceleration is supported only on the version listed at
 https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/AmlogicNPU.md#operating-system
You'll have to disable NPU acceleration if you're not using the reference version.

**Comment by edsalazarx** [comment]
there is a link for eMMc iso?, on documentation is only available for SD/USB and this build is no longer available on Khadas downloads

**Comment by edsalazarx** [comment]
Please add support to new Khadas Firmware,  the refrence version  https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/AmlogicNPU.md#operating-system 
not working on new Khadas VIM 3 Reivisions
