### ISSUE TITLE
Failed when using recognizer with command line

### ISSUE THREAD

**Issue by realDeve** [DoubangoTelecom/ultimateALPR-SDK#28]
*[ULTALPR_SDK INFO]: Starting recognizer...
*[COMPV INFO]: [UltAlprSdkEngine] Call: init
*[COMPV INFO]: [UltAlprSdkEngine] jsonConfig: {"debug_level": "info","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","num_threads": -1,"gpgpu_enabled": true,"detect_roi": [0, 0, 0, 0],"detect_minscore": 0.1,"detect_pyramidal_search_enabled": false,"recogn_minscore": 0.3,"recogn_score_type": "min","recogn_rectify_enabled": false}
*[COMPV INFO]: [UltAlprSdkEngine] **** Copyright (C) 2011-2019 Doubango Telecom <https://www.doubango.org> ****
ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK> version 2.2.1

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #4
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] Hardware: 'BCM2835', Serial: '***', Model: 'Raspberry Pi 4 Model B Rev 1.1'
*[COMPV INFO]: [CompVBase] CPU features: [arm];neon;neon_fma;vfpv3;vfpv4;
*[COMPV INFO]: [CompVBase] CPU cores: #4
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #0B, size :#0KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #3854GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: AArch32
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] Code built with option /arch:NEON
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #32
*[COMPV INFO]: [CompVBase] Best alignment: #32
*[COMPV INFO]: [CompVBase] Heap limit: #262144KB (#256MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=0,set=useless, threadId:0xb4470400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=1,set=useless, threadId:0xb3c6f400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=2,set=useless, threadId:0xb346e400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #4 threads/#4 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=3,set=useless, threadId:0xb2c6d400, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file 'C:/Projects/GitHub/ultimate/ultimateBase/lib/source/ultimate_base_engine.cxx' in function 'init' starting at line #26: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [libOpenCL.so]
*[COMPV INFO]: [UltBaseOpenCL] Failed to load [libOpenCL.so]
*[COMPV INFO]: [UltAlprSdkEnginePrivate] **** Copyright (C) 2011-2019 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK>
without the rights to include the SDK in any form of commercial product.
*[COMPV INFO]: [CompVCpu] Enabling asm code
*[COMPV INFO]: [CompVCpu] Enabling intrinsic code
***[COMPV ERROR]: function: "newObj()" 
file: "C:/Projects/GitHub/ultimate/ultimateOCR/lib/source/ultimate_ocr_charset.cxx" 
line: "58" 
message: [UltOcrCharset] Charset file at C:/Projects/GitHub/ultimate/ultimateALPR/charset_anpr_latin_size=37.txt -> /home/pi/ultimateALPR-SDK/samples/c++/recognizer/charset_anpr_latin_size=37.txt doesn't exist
***[COMPV ERROR]: function: "newObj()" 
file: "C:/Projects/GitHub/ultimate/ultimateOCR/lib/source/ultimate_ocr_recognizer.cxx" 
line: "637" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "C:/Projects/GitHub/ultimate/ultimateALPR/lib/source/ultimate_alpr_recognizer.cxx" 
line: "66" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "C:/Projects/GitHub/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_recognizer.cxx" 
line: "167" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> Failed to create Alpr recognizer
***[COMPV ERROR]: function: "init()" 
file: "C:/Projects/GitHub/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
line: "214" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [Thread] Thread with id=0xb4470400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0xb4470400) - EXIT
*[COMPV INFO]: Thread with id=0xb4470400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0xb4470400 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0xb3c6f400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0xb3c6f400) - EXIT
*[COMPV INFO]: Thread with id=0xb3c6f400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0xb3c6f400 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0xb346e400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0xb346e400) - EXIT
*[COMPV INFO]: Thread with id=0xb346e400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0xb346e400 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0xb2c6d400 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0xb2c6d400) - EXIT
*[COMPV INFO]: Thread with id=0xb2c6d400 will join
*[COMPV INFO]: [Thread] ***Thread with id=0xb2c6d400 destroyed***
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: Drawing module deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
***[COMPV ERROR]: function: "init()" 
file: "C:/Projects/GitHub/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
line: "123" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> Failed to initialize the engine
recognizer: recognizer.cxx:157: int main(int, char**): Assertion `__ULTALPR_SDK_b_ret' failed.
Aborted

**Comment by DoubangoTelecom** [comment]
The error is quite obvious. Use `--assets` option de define path to the assets folder as defined in the examples

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c++/recognizer#examples

**Comment by realDeve** [comment]
Subhanallah!!!.. This is indeed state of the art deep learning. It is working now
Thanks

**Comment by realDeve** [comment]
Moreover is there any paid version for production use?
