### ISSUE TITLE
ultimateAlprSdk.UltAlprSdkEngine_requestRuntimeLicenseKey() Error

### ISSUE THREAD

**Issue by atopcu** [DoubangoTelecom/ultimateALPR-SDK#280]
Hello,

This function does not give me runtime key. 
How can I get it from python?

Error Message:<ultimateAlprSdk.UltAlprSdkResult; proxy of <Swig Object of type 'ultimateAlprSdk::UltAlprSdkResult *' at 0x7f400ca4

Regards

**Comment by DoubangoTelecom** [comment]
Use the pre-built tools
