### ISSUE TITLE
How enable all cores on khadas VIM3

### ISSUE THREAD

**Issue by edsalazarx** [DoubangoTelecom/ultimateALPR-SDK#281]
*[COMPV INFO]: [UltAlprSdkEnginePrivate]Line in ../../../assets/models.amlogic_npu/pid_serial_mapping.txt -> [0x7D,290a]
*[COMPV INFO]: [UltAlprSdkEnginePrivate]Line in ../../../assets/models.amlogic_npu/pid_serial_mapping.txt -> [0x88,290b]
*[COMPV INFO]: [UltAlprSdkEnginePrivate]Matched PID in ../../../assets/models.amlogic_npu/pid_serial_mapping.txt: [0x88]
*[COMPV INFO]: [UltAlprSdkEnginePrivate]recogn_tf_num_threads: 6, acceleration backend: AmlogicNPU
*[COMPV INFO]: [CompVThreadDispatcher] Not optimized -> **Your system have #6 cores but you're only using #4. Sad!!**
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=0,set=useless, threadId:0x7fa8e05170, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=1,set=useless, threadId:0x7fa8604170, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #4 threads/#6 cores
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=2,set=useless, threadId:0x7fa7e03170, kThreadSetAffinity:false) - ENTER

**Comment by DoubangoTelecom** [comment]
We're using all cores. This log is from the deliverer and can be ignored. You cut the logs and if you didn't you'd see another dispatcher was created and it uses all 6 cores
