### ISSUE TITLE
Carplate font interpretation mismatch: I (letter) instead of 1 (digit)

### ISSUE THREAD

**Issue by constantintaivan** [DoubangoTelecom/ultimateALPR-SDK#283]
Hello,

We have the following issue regarding car plates recognition.
Using the production licence we get a misinterpretation of 1.
For instance in a car plate there is a number in the middle. The good read would be 21 but the actual read is 2I.

Is there any solution to avoid this font issue?

Reproduced here: https://www.doubango.org/webapps/alpr/
![image](https://github.com/DoubangoTelecom/ultimateALPR-SDK/assets/19735774/b5bbdbb1-f1ba-405d-9eb7-c78439681f6b)

Thank you
Kind regards,

**Comment by mfateminia** [comment]
Hi, to add an additional info to Constantin's point. The UK license plates (the once Constantin has also shared) are of this format:
LLDDLLL (L standing for letter and D for digit) 
Example: AB21ABC

What we have noticed is that the digits that are 1 are most of the time picked as letter "I".
Any workaround would be appreciated. 

Thanks
Ali and Constantin

**Comment by DoubangoTelecom** [comment]
Hi,
For me 4th character is an "i" not a "1". In other countries that character is an "i'. You say it's an "i" because that's the format for your country.  So, use a regular expression (LLDDLLL) to replace the 3rd and 4th characters when they are "i" to "1"
