### ISSUE TITLE
Incomplete OCR "text":"2046X*"

### ISSUE THREAD

**Issue by rndeinetworks** [DoubangoTelecom/ultimateALPR-SDK#286]
i run the repo on your image
python ../../../samples/python/recognizer/recognizer.py --image ../../../assets/images/multi.jpg --assets ../../../assets

but it gives incomplete OCR of number plate "text":"2046X*"
the last character is hidden as * character,

is this repository proving open source code ? or do we need to purchase some license

**Comment by DoubangoTelecom** [comment]
There is no mention for this project being open source
