### ISSUE TITLE
Inquiry Regarding License Purchase for ultimateALPR-SDK on Jetson Nano

### ISSUE THREAD

**Issue by MostafaMoradii** [DoubangoTelecom/ultimateALPR-SDK#288]
Dear Doubango Telecom Team,
 
I tried to contact you by email before info@doubango.org
, but I didn't get a reply, so I had to send my message here. I know it is not the right place.

We are an emerging start-up embarking on a project that necessitates the integration of advanced license plate recognition technology.
Our team has successfully deployed your ultimateALPR-SDK on a Jetson Nano device, and we are impressed with its performance.
 
Given our positive experience, we are keen to proceed with acquiring a license that is optimally suited for use on Jetson Nano hardware.
Could you provide us with a concise overview of the available licensing options?
Moreover, we are interested in understanding whether ARM licenses are compatible with Jetson Nano devices and, if so, which version would be most appropriate for our application.
 
We appreciate your guidance in helping us select the right license to ensure our project's success. Looking forward to your prompt response.

**Comment by DoubangoTelecom** [comment]
Hi,
Yes, ARM licenses are compatible with all jetson devices.
