### ISSUE TITLE
Not all Swedish license place letters are not recognized

### ISSUE THREAD

**Issue by jdahlin** [DoubangoTelecom/ultimateALPR-SDK#289]
ÅÄÖ that are valid Swedish license plates is not recognized. These are not normally issues but can be requested on a personal registration plate (personlig skylt) and there are vehicles with this kind of plates.

Reference: https://www.transportstyrelsen.se/sv/vagtrafik/fordon/om-registreringsskylt/Allmant-om-personlig-skylt/ (section Hur många och vilka tecken får du använda?)
Example plate: https://www.facebook.com/photo.php?fbid=3462157753808179&id=213233678700619&set=a.218626774827976

Å is interpreted as A
Ä is also interpreted as A
Ö is interpreted as O

**Comment by DoubangoTelecom** [comment]
Not supported
