### ISSUE TITLE
Rotated camera feed in portrait mode on Android

### ISSUE THREAD

**Issue by prateekgarg95** [DoubangoTelecom/ultimateALPR-SDK#29]
The feed is fine in landscape mode but rotated for portrait orientation

**Comment by DoubangoTelecom** [comment]
https://www.doubango.org/SDKs/anpr/docs/Frequently_Asked_Questions_(FAQ).html#why-the-image-is-90-rotated
The API version 2.4 to be released on Monday will allow rotating defining an orientation. The rotation function will be multi-threaded and SIMD-accelerated. We'll not change the UI and you'll still see the image rotated in the preview. This is done on purpose (see above link)

**Comment by prateekgarg95** [comment]
Will this be available in samples as well?

**Comment by DoubangoTelecom** [comment]
Yes

**Comment by DoubangoTelecom** [comment]
Fixed in version 2.4.0
