### ISSUE TITLE
ultimateALPR-SDK License

### ISSUE THREAD

**Issue by ramakavuri** [DoubangoTelecom/ultimateALPR-SDK#291]
Dear we are in need of your license for ultimateALPR-SDK to remove * from the last character

I am Keeping on sending email to info@doubango.org since two months kindly respond to ramakrishna@calonev.com, suresh@cal-on.com, and naveen@cal-on.com for the queries and commercial requirements

rama krishna
cal-on

**Comment by DoubangoTelecom** [comment]
Duplicates #292
