### ISSUE TITLE
Java/Maven project example

### ISSUE THREAD

**Issue by brunoaduarte** [DoubangoTelecom/ultimateALPR-SDK#32]
Hi!

This is a great project, thanks for your work!

Do you have any plans on publishing this library in a Maven repository?

Also could you provide a Java project example (non Android)?

Thank you

![image](https://user-images.githubusercontent.com/5354345/74752916-23d04580-524e-11ea-97e8-a2a4730f5f1e.png)

**Comment by DoubangoTelecom** [comment]
No, for now we're focused on mobile devices.
