### ISSUE TITLE
Error in Visual Studio

### ISSUE THREAD

**Issue by ivanh23** [DoubangoTelecom/ultimateALPR-SDK#38]
Hello , i have problem while trying to build the c++ sample in Visual Studio 2019 with 2015 build settings this error comes up

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1875,5): warning : The referenced project '..\..\..\..\SDK_dev\lib\ultimateALPR-SDK.vcxproj' does not exist.
  recognizer.cxx
recognizer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class ultimateAlprSdk::UltAlprSdkResult __cdecl ultimateAlprSdk::UltAlprSdkEngine::init(char const *,struct ultimateAlprSdk::UltAlprSdkParallelDeliveryCallback const *)" (__imp_?init@UltAlprSdkEngine@ultimateAlprSdk@@SA?AVUltAlprSdkResult@2@PBDPBUUltAlprSdkParallelDeliveryCallback@2@@Z) referenced in function _main
recognizer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class ultimateAlprSdk::UltAlprSdkResult __cdecl ultimateAlprSdk::UltAlprSdkEngine::deInit(void)" (__imp_?deInit@UltAlprSdkEngine@ultimateAlprSdk@@SA?AVUltAlprSdkResult@2@XZ) referenced in function _main
recognizer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class ultimateAlprSdk::UltAlprSdkResult __cdecl ultimateAlprSdk::UltAlprSdkEngine::process(enum ultimateAlprSdk::ULTALPR_SDK_IMAGE_TYPE,void const *,unsigned int,unsigned int,unsigned int,int)" (__imp_?process@UltAlprSdkEngine@ultimateAlprSdk@@SA?AVUltAlprSdkResult@2@W4ULTALPR_SDK_IMAGE_TYPE@2@PBXIIIH@Z) referenced in function _main
C:\Users\Ivan\Desktop\ultimateALPR-SDK-master\samples\c++\recognizer\Debug\recognizer.exe : fatal error LNK1120: 3 unresolved externals
`

**Comment by DoubangoTelecom** [comment]
Windows binaries (https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/binaries/windows) are missing. Only Android and Raspberry Pi binaries are public.

**Comment by DoubangoTelecom** [comment]
Version 2.7.0 makes Windows binaries public:
- C++ samples: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B
- C# sample: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/csharp
