### ISSUE TITLE
SDK ist just a wrapper for some languages, but the engine itself is not open source?

### ISSUE THREAD

**Issue by jmar83** [DoubangoTelecom/ultimateALPR-SDK#41]
Do i see that right?

**Comment by jmar83** [comment]
So the link https://github.com/DoubangoTelecom/ultimateALPR/tree/60a32cec92d4a3b637677153dfbeb359a16cfc65 is also dead -> https://github.com/DoubangoTelecom/ultimate is also dead.

**Comment by jmar83** [comment]
...and i can't see any price informations on your homepage!! ;-)

Thank you for your feedback.

**Comment by jmar83** [comment]
Also a 404: https://github.com/DoubangoTelecom/ultimateALPR/

:-(

**Comment by DoubangoTelecom** [comment]
Off course this is a closed source project. Why do you think it's open source?
The computer vision part (https://github.com/DoubangoTelecom/compv) is open source but not the deep learning code

**Comment by DoubangoTelecom** [comment]
BTW, you get 404 because it's private repository. Only users with the right credentials can browse the code.

**Comment by jmar83** [comment]
"You can try our SDK on your own machines using the code released on Github with full documentation hosted here. No registration, license key or internet connection is required."

Because of that - thx.

(https://www.doubango.org/webapps/alpr/)

**Comment by DoubangoTelecom** [comment]
And what?
This repository contains binaries and sample source code you can build and try on your own machines without requiring a registration or license key. This is exactly what the quote say.
You're obviously missing something. The quote doesn't say the product is open source.
