### ISSUE TITLE
Documentation has instructions to build on Windows, but the Windows binary is nowhere to be found

### ISSUE THREAD

**Issue by MikaelBrenner** [DoubangoTelecom/ultimateALPR-SDK#43]
The documentation in many points give instructions to build on Windows, like [here](https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c++/recognizer/README.md), but it's not possible to build for Windows as the binaries of the library are not available.

Could Doubango add the binaries for Windows? It's impossible to test the application on high end graphics cards at this point in time.

**Comment by DoubangoTelecom** [comment]
For now only Android and Raspberry Pi binaries are public as explained at https://www.doubango.org/SDKs/anpr/docs/Architecture_overview.html#supported-operating-systems. You can contact us (https://www.doubango.org/#contact) with your company name and information to have access to the Win64 binaries. Add information about the target CPU and GPU.

**Comment by DoubangoTelecom** [comment]
Version 2.7.0 makes Windows binaries public:
- C++ samples: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B
- C# sample: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/csharp
