### ISSUE TITLE
Error on use command to raspberry

### ISSUE THREAD

**Issue by resiprada1** [DoubangoTelecom/ultimateALPR-SDK#45]
On try add ld_library path
![image](https://user-images.githubusercontent.com/63106140/79264387-e01f4400-7e6a-11ea-8c3e-ca2369aad8c7.png)

on use g++
![image](https://user-images.githubusercontent.com/63106140/79264264-acdcb500-7e6a-11ea-9382-371a4a311e0f.png)

**Comment by DoubangoTelecom** [comment]
You're trying to build for x86 instead of arm (see "i686-linux-gnu"). You have to build for ARM using the right gcc toolchain: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#building-rpi

**Comment by DoubangoTelecom** [comment]
To make it clear, use "arm-linux-gnueabihf-g++" instead of "g++" if you don't know how to map "g++" to ARM arch

**Comment by resiprada1** [comment]
Thanks, worked, more this library is on /lib/ or /usr/lib ?
![image](https://user-images.githubusercontent.com/63106140/79336487-38515700-7efa-11ea-96dc-269cfac13b2e.png)

**Comment by resiprada1** [comment]
Thanks Doubango, i got this creating multiarch to armhf, now i receive this:

![image](https://user-images.githubusercontent.com/63106140/79340445-b284da00-7f00-11ea-9fec-134547a899f2.png)
All library already installed
sudo apt-get install libstdc++6 and lib32stdc++6

**Comment by DoubangoTelecom** [comment]
You've messed up your machine. You mixed several gcc versions with different archs. Cleanup everything and install gcc using `sudo apt install build-essential`. `lib32stdc++6` is 32-bit x86 binaries and will not work on arm.

**Comment by mirjalal** [comment]
it won't fix the error. I am still getting "error while loading shared libraries: libstdc++.so.6" 
I have already installed last version of build-essential (v12.6) & libstdc++6 (v8.3.0-6). 
My machine is RPi 4 module B with 64bit Raspberian
