### ISSUE TITLE
Referenced binaries are not available

### ISSUE THREAD

**Issue by dennisbappert** [DoubangoTelecom/ultimateALPR-SDK#49]
You mention prebuilt binaries in the PDF document which are not available in the repository. Would you mind sharing Windows binaries? (either privately or public)

**Comment by DoubangoTelecom** [comment]
As explained in the documentation, only Android and Raspberry Pi binaries are shared on Github. If you want Windows binaries you just need to send us an email (https://www.doubango.org/#contact) with your company name and we'll share them with you.

**Comment by dennisbappert** [comment]
![image](https://user-images.githubusercontent.com/7000188/80646342-d43ba080-8a6c-11ea-927c-5499df74e9fb.png)

**Comment by DoubangoTelecom** [comment]
This document was added yesterday and was private. What is important in the document is the benchmark numbers.
https://www.doubango.org/SDKs/anpr/docs/Architecture_overview.html#supported-operating-systems

**Comment by DoubangoTelecom** [comment]
Version 2.7.0 makes Windows binaries public:
- C++ samples: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B
- C# sample: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/csharp
