### ISSUE TITLE
Assertion Failed Error :  ./recognizer --image /data/India_0009.jpg

### ISSUE THREAD

**Issue by bhargavravat** [DoubangoTelecom/ultimateALPR-SDK#67]
Hi @DoubangoTelecom  : 

I am trying to run precompiled binaries on my **_x86_64_** Linux system. 

I am in to this directory  : _/data/ultimateALPR-SDK/binaries/linux/x86_64_ 
And using command :    _./recognizer --image /data/India_0009.jpg_

Attached image screen shot is the output which I am getting. 

Would be glad if you can help me out resolve the issue. 

![image](https://user-images.githubusercontent.com/11025174/86446356-7740bd00-bd31-11ea-88fc-7275f5a668af.png)

**Comment by bhargavravat** [comment]
### This is the exact log on running the command : 


*[ULTALPR_SDK INFO]: Starting recognizer...
*[COMPV INFO]: [UltAlprSdkEngine] Call: init
*[COMPV INFO]: [UltAlprSdkEngine] jsonConfig: {"debug_level": "info","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","num_threads": -1,"gpgpu_enabled": true,"detect_roi": [0, 0, 0, 0],"detect_minscore": 0.1,"pyramidal_search_enabled": true,"pyramidal_search_sensitivity": 0.28,"pyramidal_search_minscore": 0.3,"pyramidal_search_min_image_size_inpixels": 800,"recogn_minscore": 0.3,"recogn_score_type": "min","charset": "latin","recogn_rectify_enabled": false}
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx' in function 'init' starting at line #77: Not optimized -> Code not built for mobile devices but for clouds. Are you sure this is what you want?
*[COMPV INFO]: [UltAlprSdkEngine] **** Copyright (C) 2011-2020 Doubango Telecom <https://www.doubango.org> ****
ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK> version 2.8.1

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #8
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] Hardware: 'GenuineIntel', Serial: '', Model: '58', ModelName: 'Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz'
*[COMPV INFO]: [CompVBase] CPU features: (intel);[x86];[x64];mmx;sse;sse2;sse3;ssse3;sse41;sse42;avx;erms;popcnt;cmov;aes;rdrand;
*[COMPV INFO]: [CompVBase] CPU cores: #4
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #64B, size :#32KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #3670GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: X86_64
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] Code built with option /arch:SSE
*[COMPV INFO]: [CompVBase] Code built with option /arch:SSE2
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #64
*[COMPV INFO]: [CompVBase] Best alignment: #64
*[COMPV INFO]: [CompVBase] Heap limit: #262144KB (#256MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: /!\ Code in file '/home/ultimate/compv/base/compv_mem.cxx' in function 'CompVMemZero_C' starting at line #501: Not optimized -> No SIMD implementation found
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=0,set=useless, threadId:0x7fbbd5bee700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=1,set=useless, threadId:0x7fbbd53ed700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #4 threads/#4 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=2,set=useless, threadId:0x7fbbd4bec700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=3,set=useless, threadId:0x7fbbd43eb700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateBase/lib/source/ultimate_base_engine.cxx' in function 'init' starting at line #39: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [libOpenCL.so]
*[COMPV INFO]: [UltBaseOpenCL] Failed to load [libOpenCL.so]
*[COMPV INFO]: [UltAlprSdkEnginePrivate] **** Copyright (C) 2011-2020 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK>
without the rights to include the SDK in any form of commercial product.
*[COMPV INFO]: [CompVCpu] Enabling asm code
*[COMPV INFO]: [CompVCpu] Enabling intrinsic code
*[COMPV INFO]: [UltAlprSdkEnginePrivate] recogn_tf_num_threads: 4
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateOCR/lib/source/ultimate_ocr_charset.cxx" 
line: "58" 
message: [UltOcrCharset] Charset file at C:/Projects/GitHub/ultimate/ultimateALPR/charset_anpr_latin_size=37.txt -> /data/ultimateALPR-SDK/binaries/linux/x86_64/charset_anpr_latin_size=37.txt doesn't exist
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateOCR/lib/source/ultimate_ocr_recognizer.cxx" 
line: "637" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateALPR/lib/source/ultimate_alpr_recognizer.cxx" 
line: "165" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_recognizer.cxx" 
line: "167" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> Failed to create Alpr recognizer
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
line: "260" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: Drawing module deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [Thread] Thread with id=0x7fbbd5bee700 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fbbd5bee700) - EXIT
*[COMPV INFO]: Thread with id=0x7fbbd5bee700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fbbd5bee700 destroyed***
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fbbd53ed700) - EXIT
*[COMPV INFO]: [Thread] Thread with id=0x7fbbd53ed700 will join
*[COMPV INFO]: Thread with id=0x7fbbd53ed700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fbbd53ed700 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fbbd4bec700 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fbbd4bec700) - EXIT
*[COMPV INFO]: Thread with id=0x7fbbd4bec700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fbbd4bec700 destroyed***
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fbbd43eb700) - EXIT
*[COMPV INFO]: [Thread] Thread with id=0x7fbbd43eb700 will join
*[COMPV INFO]: Thread with id=0x7fbbd43eb700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fbbd43eb700 destroyed***
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
line: "126" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> Failed to initialize the engine
****[ULTALPR_SDK FATAL]: function: "main()" 
file: "/home/ultimate/ultimateALPR/SDK_dist/samples/c++/recognizer/recognizer.cxx" 
line: "183" 
message: Assertion failed!
Aborted (core dumped)
root@dd595e18c4d2:/data/ultimateALPR-SDK/binaries/linux/x86_64# 
root@dd595e18c4d2:/data/ultimateALPR-SDK/binaries/linux/x86_64# ./recognizer --image /data/StatewiseDataSet/Jammu/Jammu_0001.jpg 
*[ULTALPR_SDK INFO]: Starting recognizer...
*[COMPV INFO]: [UltAlprSdkEngine] Call: init
*[COMPV INFO]: [UltAlprSdkEngine] jsonConfig: {"debug_level": "info","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","num_threads": -1,"gpgpu_enabled": true,"detect_roi": [0, 0, 0, 0],"detect_minscore": 0.1,"pyramidal_search_enabled": true,"pyramidal_search_sensitivity": 0.28,"pyramidal_search_minscore": 0.3,"pyramidal_search_min_image_size_inpixels": 800,"recogn_minscore": 0.3,"recogn_score_type": "min","charset": "latin","recogn_rectify_enabled": false}
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx' in function 'init' starting at line #77: Not optimized -> Code not built for mobile devices but for clouds. Are you sure this is what you want?
*[COMPV INFO]: [UltAlprSdkEngine] **** Copyright (C) 2011-2020 Doubango Telecom <https://www.doubango.org> ****
ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK> version 2.8.1

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #8
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] Hardware: 'GenuineIntel', Serial: '', Model: '58', ModelName: 'Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz'
*[COMPV INFO]: [CompVBase] CPU features: (intel);[x86];[x64];mmx;sse;sse2;sse3;ssse3;sse41;sse42;avx;erms;popcnt;cmov;aes;rdrand;
*[COMPV INFO]: [CompVBase] CPU cores: #4
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #64B, size :#32KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #3670GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: X86_64
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] Code built with option /arch:SSE
*[COMPV INFO]: [CompVBase] Code built with option /arch:SSE2
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #64
*[COMPV INFO]: [CompVBase] Best alignment: #64
*[COMPV INFO]: [CompVBase] Heap limit: #262144KB (#256MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: /!\ Code in file '/home/ultimate/compv/base/compv_mem.cxx' in function 'CompVMemZero_C' starting at line #501: Not optimized -> No SIMD implementation found
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=0,set=useless, threadId:0x7fd8e4c96700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=1,set=useless, threadId:0x7fd8e4495700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=2,set=useless, threadId:0x7fd8e3c94700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #4 threads/#4 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=3,set=useless, threadId:0x7fd8e3493700, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateBase/lib/source/ultimate_base_engine.cxx' in function 'init' starting at line #39: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [libOpenCL.so]
*[COMPV INFO]: [UltBaseOpenCL] Failed to load [libOpenCL.so]
*[COMPV INFO]: [UltAlprSdkEnginePrivate] **** Copyright (C) 2011-2020 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK>
without the rights to include the SDK in any form of commercial product.
*[COMPV INFO]: [CompVCpu] Enabling asm code
*[COMPV INFO]: [CompVCpu] Enabling intrinsic code
*[COMPV INFO]: [UltAlprSdkEnginePrivate] recogn_tf_num_threads: 4
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateOCR/lib/source/ultimate_ocr_charset.cxx" 
line: "58" 
message: [UltOcrCharset] Charset file at C:/Projects/GitHub/ultimate/ultimateALPR/charset_anpr_latin_size=37.txt -> /data/ultimateALPR-SDK/binaries/linux/x86_64/charset_anpr_latin_size=37.txt doesn't exist
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateOCR/lib/source/ultimate_ocr_recognizer.cxx" 
line: "637" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateALPR/lib/source/ultimate_alpr_recognizer.cxx" 
line: "165" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
***[COMPV ERROR]: function: "newObj()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_recognizer.cxx" 
line: "167" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> Failed to create Alpr recognizer
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_private_engine.cxx" 
line: "260" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> 
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: Drawing module deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [Thread] Thread with id=0x7fd8e4c96700 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fd8e4c96700) - EXIT
*[COMPV INFO]: Thread with id=0x7fd8e4c96700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fd8e4c96700 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fd8e4495700 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fd8e4495700) - EXIT
*[COMPV INFO]: Thread with id=0x7fd8e4495700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fd8e4495700 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fd8e3c94700 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fd8e3c94700) - EXIT
*[COMPV INFO]: Thread with id=0x7fd8e3c94700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fd8e3c94700 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fd8e3493700 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fd8e3493700) - EXIT
*[COMPV INFO]: Thread with id=0x7fd8e3493700 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fd8e3493700 destroyed***
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
line: "126" 
message: Operation Failed (COMPV_ERROR_CODE_E_FILE_NOT_FOUND) -> Failed to initialize the engine
****[ULTALPR_SDK FATAL]: function: "main()" 
file: "/home/ultimate/ultimateALPR/SDK_dist/samples/c++/recognizer/recognizer.cxx" 
line: "183" 
message: Assertion failed!
Aborted (core dumped)

**Comment by DoubangoTelecom** [comment]
Add --assets option as explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B/recognizer#testing-examples
```
./recognizer  --image /data/India_0009.jpg  --assets ../../../assets
```
