### ISSUE TITLE
Running the SDK in Python

### ISSUE THREAD

**Issue by OctaM** [DoubangoTelecom/ultimateALPR-SDK#7]
Hello and thanks for your work,

In the documentation it says that it can be used in Python but I didn't find any example or documentation regarding how to use it with Python. Can you please point me in the right direction?

Thanks

**Comment by DoubangoTelecom** [comment]
Yes python is supported but there is no documentation yet. For now we only have documentation for Java and C++.

**Comment by OctaM** [comment]
Thanks for the answer. Is there any way that I can start using it in Python? I do not really need a documentation, but just some hints about how can I start and I think I can figure it out.

**Comment by realDeve** [comment]
I also need to use this with python and raspberry pi 3

**Comment by NEgadai** [comment]
following.

**Comment by KamalChhirang** [comment]
Same here, I want some kind of hint on how to run it on Python. You did such amazing work, really!

**Comment by rahulsharma22-ops** [comment]
I am also wondering, how to run Python code. How can I install _ultimateAlprSdk

**Comment by wveldencap** [comment]
Is there already anyone that has an answer to this question. I would really like to play around with this SDK in python

**Comment by DoubangoTelecom** [comment]
Fix in 2.11.0. Recognizer sample: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer
