### ISSUE TITLE
Error : While Building recognizer executable 

### ISSUE THREAD

**Issue by bhargavravat** [DoubangoTelecom/ultimateALPR-SDK#74]
Hi @DoubangoTelecom  : 

I am trying to build **executable of recognize**r , however unable to build it. 

I followed steps given in README.md . 

Here is the error output. ****
![image](https://user-images.githubusercontent.com/11025174/86996279-daff3600-c1c8-11ea-9fd2-d8861059c475.png)

**Comment by bhargavravat** [comment]
Here is the exact log of the output:

I am into directory :
`/data/ultimateALPR-SDK/samples/c++/recognizer`

This is the command which I am running :
`g++ recognizer.cxx -O3 -I../../../c++ -L../../../binaries/linux/x86_64 -lultimate_alpr-sdk -o recognizer`

This is output which I am getting :
`/usr/bin/ld: warning: libtensorflow.so.1, needed by ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_Message@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_GraphGetTensorNumDims@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DeleteImportGraphDefOptions@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_SessionRun@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DeleteGraph@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_NewSessionOptions@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_GraphImportGraphDef@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_NewStatus@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DataTypeSize@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_SetConfig@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_NewImportGraphDefOptions@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_CloseSession@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DeleteSession@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DeleteTensor@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_GetCode@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_NewGraph@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DeleteStatus@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DeleteBuffer@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_TensorType@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_GraphGetTensorShape@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_TensorData@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_TensorByteSize@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_GraphOperationByName@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_NumDims@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_NewBuffer@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_Dim@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_NewSession@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_AllocateTensor@VERS_1.0'
/usr/bin/ld: ../../../binaries/linux/x86_64/libultimate_alpr-sdk.so: undefined reference to `TF_DeleteSessionOptions@VERS_1.0'
collect2: error: ld returned 1 exit status
`

**Comment by DoubangoTelecom** [comment]
You need libtensorflow.so -> https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c%2B%2B/README.md#gpu-acceleration-tensorflow-linux

**Comment by mochechan** [comment]
After following [https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c%2B%2B/README.md#gpu-acceleration-tensorflow-linux](https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c%2B%2B/README.md#gpu-acceleration-tensorflow-linux), the problem is still existing. Any suggestion?
![fail2compile](https://user-images.githubusercontent.com/6790977/125426120-32483bdd-68ad-44d2-bedf-735a24be9852.png)

**Comment by DoubangoTelecom** [comment]
> After following https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c%2B%2B/README.md#gpu-acceleration-tensorflow-linux, the problem is still existing. Any suggestion?
> ![fail2compile](https://user-images.githubusercontent.com/6790977/125426120-32483bdd-68ad-44d2-bedf-735a24be9852.png)

Link to tensorflow library `-ltensorflow`

**Comment by mochechan** [comment]
> 
> Link to tensorflow library `-ltensorflow`

Success. Thank you. 

Additional question: How to setup CMakeLists.txt rather than using g++ directly?
The CMakeLists.txt in ultimateALPR-SDK/samples/c++/recognizer/ has some problems.

![failcmake](https://user-images.githubusercontent.com/6790977/125591875-8cf9d431-f4e1-48c0-a5b6-a8bf3a680c89.png)

**Comment by DoubangoTelecom** [comment]
> > Link to tensorflow library `-ltensorflow`
> 
> Success. Thank you.
> 
> Additional question: How to setup CMakeLists.txt rather than using g++ directly?
> The CMakeLists.txt in ultimateALPR-SDK/samples/c++/recognizer/ has some problems.
> 
> ![failcmake](https://user-images.githubusercontent.com/6790977/125591875-8cf9d431-f4e1-48c0-a5b6-a8bf3a680c89.png)

These CMake files have dependencies on private code. We think it's useless to create one for a single file. If you still want one use https://github.com/DoubangoTelecom/FaceLivenessDetection-SDK/blob/master/samples/cpp/liveness/CMakeLists.txt.:
Some changes:
- `project (liveness VERSION 1.0.0 LANGUAGES CXX C)` -> `project (recognizer VERSION 1.0.0 LANGUAGES CXX C)`
- `${CMAKE_CURRENT_SOURCE_DIR}/../../../cpp` -> `${CMAKE_CURRENT_SOURCE_DIR}/../../../c++`
- `libFaceLivenessDetectionSDK.so` -> `libultimate_alpr-sdk.so` 
- and add libtensorflow to target_link_libraries(...)
... haven't tested but I think that's it.

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/ultimateALPR-SDK/issues/162
