### ISSUE TITLE
Processing on Video file

### ISSUE THREAD

**Issue by bhargavravat** [DoubangoTelecom/ultimateALPR-SDK#77]
Hi @DoubangoTelecom :

Presently I am able to run **recognizer binary** for the single still image. 

What changes are to be made in order to run it on _video / live RTSP feed_ ?

Thanks and regards,
Bhargav

**Comment by DoubangoTelecom** [comment]
We only provide the ALPR/ANPR functions. You can use libraries like OpenCV or ffmpeg to capture images from rtsp stream (e.g. https://stackoverflow.com/questions/21041370/opencv-how-to-capture-rtsp-video-stream) and provide the images to the process function (https://www.doubango.org/SDKs/anpr/docs/cpp-api.html#_CPPv4N15ultimateAlprSdk16UltAlprSdkEngine7processEK22ULTALPR_SDK_IMAGE_TYPEPKvK6size_tK6size_tK6size_tKi)
