### ISSUE TITLE
Processing Raw Images

### ISSUE THREAD

**Issue by bhargavravat** [DoubangoTelecom/ultimateALPR-SDK#83]
Hi @DoubangoTelecom : 

I am trying to process raw byte array of image which I receive using socket connection, however unable to decode the same using alprDecodeFile() function , but unable to do. 

Is there any head way for this ?

**Comment by DoubangoTelecom** [comment]
If the image is raw format it means it's uncompressed and doesn't make sens to decode. Also if you're receiving it from a socket yoi cannot use alprDecodeFile() which accepts a file. Your report is confusing. You should provide more information and code sample.
