### ISSUE TITLE
Add Java wrapper (JNI interface) to ARM

### ISSUE THREAD

**Issue by josh256** [DoubangoTelecom/ultimateALPR-SDK#84]
Java wrappers are missing for Raspbian.

**Comment by DoubangoTelecom** [comment]
Version 2.11 adds Java to Linux and Windows x86_64, Python to all archs and OSes.

**Comment by josh256** [comment]
Java wrappers to arch ARM?

**Comment by DoubangoTelecom** [comment]
> Java wrappers to arch ARM?

no
