### ISSUE TITLE
RTSP Player insteadof Camera

### ISSUE THREAD

**Issue by khyatiChitroda** [DoubangoTelecom/ultimateALPR-SDK#85]
I want to run this on live rtsp or rtmp view in android application, does it possible? as of now this is working with camera and GLSurfaceview, but I want to run this on Live streaming feed.

**Comment by DoubangoTelecom** [comment]
This is out of scope. You're asking how dev rtsp/rtmp application on Android, not related to ANPR. We're providing an ANPR SDK accepting a raw image as input and returning the result. We provide samples showing how to use with a camera or local file. For other sources (rtsp, multipart, rtp...) it's up to you. I'd recommend using OpenCV
