### ISSUE TITLE
Wrong url: SIMD- information message on raspi 4

### ISSUE THREAD

**Issue by wesimet** [DoubangoTelecom/ultimateALPR-SDK#87]
Hi Doubango- Team

I use Raspi 4. It gives the following information message:
/!\ Code in file '/home/ultimate/compv/base/compv_mem.cxx' in function 'CompVMemCopy_C' starting at line #953: Not optimized -> No SIMD implementation found. On ARM consider http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka13544.html

The url is wrong: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka13544.html.
Is there a new url? What should I do?

thx

**Comment by DoubangoTelecom** [comment]
This is just a warning for the developer that the function is not fully optimized with ARM Neon code. You can safely ignore it.
