### ISSUE TITLE
Small plates removed after Pysearch

### ISSUE THREAD

**Issue by wesimet** [DoubangoTelecom/ultimateALPR-SDK#98]
Hi DoubangoTelecom- Team

When i check frames, i have a lot of informational messages:

*[COMPV INFO]: [UltAlprPysearch] Small plates removed after Pysearch: 1 -> 0

What does that mean? Do I have to improve something?

Thx

**Comment by DoubangoTelecom** [comment]
This is just to inform that some plates are too small to be readable and were rejected instead of being provided to the OCR
